### ISSUE TITLE
Question: Are you planning on making something like this for pvAccess?

### ISSUE THREAD

**Issue by thomascobb** [caproto/caproto#100]
Just curious, seems like a nice approach...

**Comment by klauer** [comment]
It's been something we've been talking about for a while. My (personal) view of the project roadmap is first getting the V3 stuff in solidly (various clients and curio-based server, including some nice utilities for caproto-based soft IOC creation) then begin working toward a pure-Python V4/pvAccess implementation.

As this is a side-project for everyone involved, getting to that point may take a while.

**Comment by hhslepicka** [comment]
Sorry, wrong click!
As `caproto-based` soft IOC creation do you mean something like what we can do with pcaspy?

**Comment by klauer** [comment]
@hhslepicka caproto can already do most of what pcaspy can in terms of acting as a channel access server. We're brainstorming various ways to make it easy to stand up a server in a pythonic way - one perhaps loosely based on the `ophyd.Device`-like suggestion of #79.

**Comment by danielballan** [comment]
Thanks @thomascobb, glad to hear you like the approach. I agree with @klauer's sense of our roadmap. It's possible I may get a week or two later this year to deeply focus on extending caproto to v4, but I would not want to begin that work until our v3 components are fully fleshed out and benchmarked.

**Comment by thomascobb** [comment]
Good to know. I'm currently using pvaPy in [Malcolm](http://pymalcolm.readthedocs.io) (Diamond's continuous scanning framework, a bit like the fly scan bits of ophyd and bluesky but with a pva interface) and I'm finding the boost-python wrapping of C++ very error prone. Are any of you going to ICALEPCS? It might be useful to discuss there...

**Comment by stuartcampbell** [comment]
Hi @thomascobb unfortunately, non of us are going to ICALEPCS.  There will be NSLS-II folks there but no one that has working on this.  There are some discussions about coming to visit Diamond for other collaborations reasons in the near future, but otherwise we can always arrange a video call if that would be useful.

**Comment by danielballan** [comment]
In case you hadn't caught it @thomascobb, work in progress is here: https://github.com/NSLS-II/caproto/pull/152

This plan is still to nail down v3 first.

**Comment by matthew-d-jones** [comment]
PVA support would make caproto a really useful tool for us working on software for the ESS. It looks like prototyping work was done but no implementation made it to `master`, is that right?

**Comment by danielballan** [comment]
Correct. The author of that work is not interested in proceeding with it. If someone at the ESS has the interest in and resource for picking it up, I can be available to help them get oriented in the structure and design of this codebase.

**Comment by thomascobb** [comment]
Just for the record, we ended up using [p4p](https://mdavidsaver.github.io/p4p/) instead. It works with threads and asyncio and does what we need it to do. I would still be interested to see where this goes though if ESS was to pick it up, pure Python libraries are definitely more flexible...

**Comment by matthew-d-jones** [comment]
@danielballan @thomascobb Thanks for the replies, I'll be in touch if we decide to pick it up.

**Comment by tacaswell** [comment]
I still have interest (but no time) in formalizing a way to publish a modern industry standard binary format (msgpack, arrow, protobuf, flatbuffer, ...) over CA.  You get all the benefits of V4 (structured data!) without any of the downsides.

**Comment by hhslepicka** [comment]
Dropping this here just in case: https://github.com/epics-base/pvAccessCPP/wiki/protocol
It is my understanding that it was updated recently when Kay Kasemir produced the new Java library for PVAccess.

**Comment by matthew-d-jones** [comment]
@tacaswell In our system we serialise data from EPICS (CA and PVA) using google flatbuffers and forward them into Apache Kafka. This is our current flatbuffer schema for EPICS data: https://github.com/ess-dmsc/streaming-data-types/blob/master/schemas/f142_logdata.fbs

@hhslepicka Thanks for the link

**Comment by danielballan** [comment]
@thomascobb @matthew-d-jones The work on PVA support has been revived and is poised to be merged. It is highly experimental at this point, but it's a going concern. https://github.com/caproto/caproto/pull/636
