### ISSUE TITLE
Sort out how circuit properties get set on the server side.

### ISSUE THREAD

**Issue by danielballan** [caproto/caproto#234]

**Comment by klauer** [comment]
What does this mean... ?

**Comment by danielballan** [comment]
Some circuit properties, are set after `__init__` time because they are not immediately known. When I create this issue (hastily...) the circuit's priority was never being set. I believe that is still the case.

**Comment by klauer** [comment]
Just checked with the current master. `VirtualCircuit.priority` is being set on the server side when `VersionRequest` rolls by. This is the earliest it can possibly happen and appears correct to me.
