### ISSUE TITLE
Get appveyor fully passing

### ISSUE THREAD

**Issue by danielballan** [caproto/caproto#243]
All of the components now work on Windows, but appveyor isn't _quite_ passing. Current standing:

```
6 failed, 1513 passed, 11 skipped, 2 xfailed, 1 xpassed, 1 warnings
```

We should fix, skip, or xfail those 6 tests to get a build the passes.

**Comment by danielballan** [comment]
Punting this back to v0.2.1 because it's too big of a job. I spot-checked the three servers and the CLIs on Windows and patched up a problem in #363. Other than that, there does not appear to be anything show-stopping.

**Comment by klauer** [comment]
Or get azure working, but that may be even more difficult...

**Comment by klauer** [comment]
Appveyor is no longer in use.
