### ISSUE TITLE
Consider flipping default of 'wait' in threading write() method for consistency

### ISSUE THREAD

**Issue by danielballan** [caproto/caproto#273]
I'm not strongly inclined to do this right before the v0.1.0 release, but it does bug me that we aren't consistent about it.

**Comment by danielballan** [comment]
Is this still something we want to do? The default is currently to block `wait=True` which makes this inconsistent with the behavior of the sync client and the commandline client. The strongest reason for flipping the default is that not all IOCs, even modern ones, can handle `WriteNotifyRequest`, so defaulting to a plain `WriteRequest`, as the sync and commandline clients do, is arguably better behavior.

**Comment by tacaswell** [comment]
:+1:  I think in ophyd we are always explicit about what we want to do so I don't think it will break us there.

**Comment by klauer** [comment]
It may be too late for this one, regardless of inconsistency...

**Comment by danielballan** [comment]
I could defend our current approach (use put completion by default) from the point of view that put completion should be used wherever it is available. Closing in agreement with @klauer. Reopen if there is more to discuss here.
