### ISSUE TITLE
Make timeouts scale by data_count and, for batches, number of channels.

### ISSUE THREAD

**Issue by danielballan** [caproto/caproto#284]

**Comment by klauer** [comment]
At least - maybe!

**Comment by danielballan** [comment]
From what we learned in https://github.com/bluesky/ophyd/pull/788, the timeout seems to be dominated by waiting for the server to process its queues. The _transfer_ time must scale linearly with `data_count` but that seems to be a small fraction of the overall time budget required for practical use. Thus, I think constant timeouts are correct.
