### ISSUE TITLE
Document logging best practices / logging verbosity

### ISSUE THREAD

**Issue by klauer** [caproto/caproto#417]
In ophyd, due to the caproto client being slightly less stable than the pyepics client, tests frequently time out. Due to the extreme verbosity of logging, this can cause issues with Travis CI:

```
...
[D 00:52:36.186 _broadcaster:106] 56 bytes -> SearchRequest(name='81812cb1:dxp:CalibrationEnergy_RBV', cid=2896, version=13, reply=5)
[D 00:52:36.186 _broadcaster:106] 48 bytes -> SearchRequest(name='81812cb1:dxp:CurrentPixel', cid=2897, version=13, reply=5)
[D 00:52:36.187 _broadcaster:106] 48 bytes -> SearchRequest(name='81812cb1:dxp:DynamicRange_RBV', cid=2898, version=13, reply=5)
[D 00:52:36.187 _broadcaster:106] 48 bytes -> SearchRequest(name='81812cb1:dxp:PresetEvents_RBV', cid=2899, version=13, reply=5)
[D 00:52:36.187 _

The job exceeded the maximum log length, and has been terminated.
```
(full [log](https://api.travis-ci.org/v3/job/479668433/log.txt); ~10,000 lines clipped of failed test; total 28,153 line travis output)

I think we need to define best practices here before others run into such issues. The following groups of what users might want to see could possibly be broken up into the following categories:
1. Where PVs are coming from / network configuration (`Broadcaster`: `SearchRequest`, `SearchResponse`, `Beacon`)
2. Debug writes and reads (PV: `ReadRequest`, `WriteRequest` and responses)
3. (What goes here?)
4. Ability to filter the above based on PV name: one problematic PV should not require opening the floodgates
5. No debugging required whatsoever - return values and `Exception`s suffice

**Comment by danielballan** [comment]
1. Use 'caproto.bcast'
2. Use 'caproto.ch'
4. Use 'caproto.ch.<name>'
5. The default configuration gives you WARNING and ERROR, but you can turn those off by removing the handler (`getLogger('caproto').handlers.clear()`).

Would it be useful to outline your categories in the Useful Snippets section of this [logger docs](https://nsls-ii.github.io/caproto/loggers.html)?

**Comment by klauer** [comment]
Definitely useful to outline them and add in some copy/paste-able examples.

It seems like following one PV from search, to creation and destruction should be a trivial operation from a user's standpoint.  There is nice granularity with `caproto.ch.<name>.<priority>`, but the same is not possible with `caproto.bcast`.

**Comment by danielballan** [comment]
Good point. How about:

```
caproto.bcast
caproto.bcast.search  # omits the beacon noise
caproto.bcast.search.name
```

**Comment by danielballan** [comment]
OK, then the task here is to find places where we use the `caproto.bcast` logger and use a new, more specific loggers instead. This is a backward compatible change because all the log messages to `caproto.bcast.search` and `caproto.bcast.<some_pv_name>` will also propagate up to the existing `caproto.bcast`.

I have some reservations about the performance implications (lots of new calls to `getLogger` in a hot loop maybe?) but it's worth sketching it up and finding out how it looks/performs.

@ke-zhang-rd -- I think this is a good place for you to start digging into caproto logging.

**Comment by danielballan** [comment]
For our collective future reference, here is [Python's cookbook entry on `LoggingAdapter`](https://docs.python.org/3/howto/logging-cookbook.html#using-loggeradapters-to-impart-contextual-information) which may be a better way to carry PV-specific info than have very-nested loggers, as we have had for some time in `PV` and have just added to `Broadcaster` in #427.

**Comment by klauer** [comment]
I think this is in a pretty good state now with the logging refactor + documentation. Closing.
