### ISSUE TITLE
Resolve OSError from premature call to getsockname() on Windows

### ISSUE THREAD

**Issue by danielballan** [caproto/caproto#514]
Starting in v0.4.0, we call `sock.getsockname()` in many places to obtain "our address" for logging purposes. Apparently, we sometimes do this on an _unbound_ socket, which [reportedly raises an error "on Windows"](https://mail.python.org/pipermail/python-list/2015-January/683777.html) but I guess returns without an error on Linux/OSX. (Not sure what it would return....)

This error on Windows was observed and reported in by @mrakitin and @EliotGann in https://github.com/nsls-ii-forge/caproto-feedstock/issues/2. The key section is:

```
~\.conda\envs\collection-nsls2forge-py37-defaults\lib\site-packages\caproto\threading\pyepics_compat.py in PV()
    170                'upper_warning_limit', 'upper_ctrl_limit', 'lower_ctrl_limit',
    171                'put_complete')
--> 172     _default_context = Context(SharedBroadcaster())
    173
    174     def __init__(self, pvname, callback=None, form='time',

~\.conda\envs\collection-nsls2forge-py37-defaults\lib\site-packages\caproto\threading\client.py in __init__(self, registration_retry_time)
    340
    341         self.broadcaster = ca.Broadcaster(our_role=ca.CLIENT)
--> 342         self.broadcaster.our_address = self.udp_sock.getsockname()[:2]
    343         self.log = logging.LoggerAdapter(
    344             self.broadcaster.log, {'role': 'CLIENT'})

OSError: [WinError 10022] An invalid argument was supplied

In [1]:
```

Our intent was to only call `getsockname()` after the socket is bound. There a couple places where the code goes out of its way to call it as early as possible but no earlier. It looks like we didn't get that quite right. The best fix would be to avoid calling `getsockname()` on an unbound socket. If we can't figure out that, a stop-gap could be to make some `safe_getsockname` that swallows the `OSError`.

cc @ke-zhang-rd

**Comment by mrakitin** [comment]
Thanks for documenting it @danielballan!
