### ISSUE TITLE
"Try caproto in four lines" - Error occurred

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#515]
I am trying to get become familiar with the caproto project. I have started with reading the documentation and trying things. 

I have tried this [try-caproto-in-four-lines](https://caproto.github.io/caproto/#try-caproto-in-four-lines) and I am getting errors.

OS: Mac OS Mojave
Python: 3.7.4

```
user:Software user-13$ python3 --version
Python 3.7.4
user:Software user-13$ python3 -m pip install -U caproto
Collecting caproto
  Downloading https://files.pythonhosted.org/packages/7e/24/0baa65557e866082333290ade07e20962188d17695df881a964a84d266d4/caproto-0.4.0-py3-none-any.whl (308kB)
     |████████████████████████████████| 317kB 6.4MB/s 
Installing collected packages: caproto
Successfully installed caproto-0.4.0
user:Software user-13$ python3 -m caproto.ioc_examples.simple --list-pvs
[I 09:29:53.665          server:  161] Asyncio server starting up...
[I 09:29:53.665          server:  174] Listening on 0.0.0.0:5064
[I 09:29:53.666          server:  260] Server startup complete.
[I 09:29:53.667          server:  262] PVs available:
    simple:A
    simple:B
    simple:C
[E 09:29:53.693          common:  665] Broadcaster command queue evaluation failed
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/server/common.py", line 660, in broadcaster_queue_loop
        await self._broadcaster_queue_iteration(addr, commands)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/server/common.py", line 707, in _broadcaster_queue_iteration
        self.broadcaster.process_commands(commands)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/_broadcaster.py", line 142, in process_commands
        self._process_command(self.their_role, command, history)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/_broadcaster.py", line 159, in _process_command
        raise err("A broadcasted SearchResponse must be preceded by a "
    caproto._utils.RemoteProtocolError: A broadcasted SearchResponse must be preceded by a VersionResponse in the same datagram.

------error repeats every 5 ms--------

^C[I 09:41:59.964          server:  267] Server task cancelled. Will shut down.
[I 09:41:59.964          server:  281] Server exiting....
```

**Comment by tacaswell** [comment]
are there other epics things on the network?  Can you try starting with `-vvv` as well?

**Comment by vstadnytskyi** [comment]
@tacaswell 
We do have other IOCs running on the network.

```
$ python3 -m caproto.ioc_examples.simple --list-pvs -vvv

[D 10:07:33.865    _broadcaster:  130] [0.0.0.0:5064] <<<--- [128.231.5.169:63337] (32B) SearchRequest(name='NIH:CHILLER.I2s', cid=18, version=11, reply=5) 
[D 10:07:33.862    _broadcaster:  130] [0.0.0.0:5064] <<<--- [128.231.5.169:63337] (40B) SearchRequest(name='NIH:CHILLER.HLMs', cid=16, version=11, reply=5)

And many many others.
```

**Comment by tacaswell** [comment]
Ah, I think what is going on is that your client is not technically following the rules (there needs to be a version request ahead of a search request) and caproto is complaining about it.

Not sure why something is searching for PVs at 20hz though...

**Comment by vstadnytskyi** [comment]
> Ah, I think what is going on is that your client is not technically following the rules (there needs to be a version request ahead of a search request) and caproto is complaining about it.
> 
> Not sure why something is searching for PVs at 20hz though...

Are

**Comment by vstadnytskyi** [comment]
I didn't mean to close it. 

@tacaswell 
Are you saying that there are clients that search for PVs at 200Hz (1/5 ms)?

**Comment by tacaswell** [comment]
Right 200Hz, I can do math...

Either we are not doing a good job at throwing bogus messages off the work queue or you have a very noisy client(s).

**Comment by tacaswell** [comment]
With only one client from `ca_python` I can not reproduce the 200hz issue.  What I see is 
 - the first time I search I get 3 trace backs (because it is seeing 3x udp broadcast from local loopback, the real ethernet, and docker's interface)
 - if I search again I see 3x at 1s intervals
 

I can see having ~200 / s if you have 75-100 PVs all searching once a second.

See https://github.com/friedrich-schotte/ca_python/pull/1 for a fix to the protocol violation.

**Comment by danielballan** [comment]
Could there be other _client_ programs running on the network that are stuck in a search loop looking for PVs that they will never find? That might be the origin of the 75-100 searches.

**Comment by danielballan** [comment]
Also, the [`caproto-shark` utility](https://caproto.github.io/caproto/shark.html) might be useful for investigating where those searches are coming from. But with @tacaswell's fix above, a bunch of background traffic shouldn't matter.

**Comment by vstadnytskyi** [comment]
> With only one client from `ca_python` I can not reproduce the 200hz issue. What I see is
> 
> * the first time I search I get 3 trace backs (because it is seeing 3x udp broadcast from local loopback, the real ethernet, and docker's interface)
> * if I search again I see 3x at 1s intervals
> 
> I can see having ~200 / s if you have 75-100 PVs all searching once a second.
> 
> See [friedrich-schotte/ca_python#1](https://github.com/friedrich-schotte/ca_python/pull/1) for a fix to the protocol violation.

Thanks. 

Unfortunately, I have submitted an outdated link to our home-built repository and I have edited my comment above to reflect a correct [one](https://github.com/friedrich-schotte/EPICS_CA). Sorry! 

The last fix (fifth one) actually addresses the bug and is a simple fix. I think I can just do that first and look into the rest later.

**Comment by tacaswell** [comment]
new PR: https://github.com/friedrich-schotte/EPICS_CA/pull/3

**Comment by danielballan** [comment]
Looks like this is resolved. Please re-open if needed. Thanks!
