### ISSUE TITLE
clients documentation question

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#517]
I was wondering if it is wise to add links explaining what us the fundamental difference between different client types. There are four different clients in caproto, and from first glance, I don't see how to take advantage of each of them. It seems to me that "Synchronous Client" will be my first choice and I will only work with it. 

- Synchronous Client
- Threading Client
- Pyepics-Compatible Client
- Asynchronous Clients

**Comment by klauer** [comment]
From my perspective:
* The synchronous clients are simplistic but functional, easy to read and understand what happens with a single `get`, `put`, `monitor` operation - (or repeater/shark, which are somewhat off to the side). These are perfectly fine to be used in isolation, but should not be used to build larger programs.
* Asynchronous clients - these are experimental and not very solid. We'd like to rework and build these out again at some point. Of note, there is no asyncio client currently, just curio/trio.
* Threading client - this is generally our recommended client with the most features and testing behind it. 
  - The pyepics-compatibility layer should only be used if you want to upgrade some old pyepics-only code.

**Comment by danielballan** [comment]
New clients landing page: https://caproto.github.io/caproto/clients.html

Thanks for the feedback, @vstadnytskyi. It’s valuable to have fresh eyes on this documentation.
