### ISSUE TITLE
difference between time.sleep and async_lib.library.sleep python

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#518]
The [Random Walk IOC example](https://caproto.github.io/caproto/iocs.html#random-walk) has a sleep section that uses async_lib.library.sleep() instead of time.sleep(). What is the difference and where does this async_lib.library.sleep come from? I don't see it been explicitly imported anywhere.

**Comment by klauer** [comment]
As caproto supports three different async libraries, we have an "async layer" class that gives compatible async versions of commonly used synchronization primitives - such as https://github.com/caproto/caproto/blob/a824f1e5c95dada34f7ab0dcc3b3ca62a49a0ffa/caproto/asyncio/server.py#L51 for asyncio. All of the libraries we currently support offer a `sleep` function at the top-level, allowing us to just use it directly. That is, `async_lib.library` would be either the module`asyncio`, `trio`, or `curio`, and `.sleep` would give the appropriate sleep method for each library.

As to "why not `time.sleep`?" - that's a fundamental asyncio question, which might be better answered elsewhere (perhaps https://stackoverflow.com/questions/46207991/what-does-yield-from-asyncio-sleepdelay-do)

The gist is that `asyncio.sleep` doesn't hold up your entire thread/event loop, but gives back control to the event loop to run other tasks while sleeping. `time.time`, on the other hand, would cause noticeable delays and problems.

**Comment by vstadnytskyi** [comment]
A lot of my questions arise from the fact that I have never used AsyncIO and I've never read about it.  I have found few good resources:
[on concurrency](https://realpython.com/python-concurrency/)
[on async io ](https://realpython.com/async-io-python/)

**Comment by klauer** [comment]
It may be out of the scope of the caproto project to teach asyncio concepts from scratch, but maybe we could at least link to the resources @vstadnytskyi provided in the documentation - thoughts @mrakitin @danielballan?

**Comment by vstadnytskyi** [comment]
> It may be out of the scope of the caproto project to teach asyncio concepts from scratch, but maybe we could at least link to the resources @vstadnytskyi provided in the documentation - thoughts @mrakitin @danielballan?

The project is orientated for the user who needs to create their own IOC's etc. It will make it easier to understand how to use caproto if the user can educate themselves on these new concepts. A lot of researchers, I work with, use Python 2.7 and transition to Python 3 is not easy. We are creatures of habit. I think having some "Further reading" section very handy.

**Comment by mrakitin** [comment]
I like the idea of having a couple of links about general async programming 🙂.

**Comment by danielballan** [comment]
Closed by #528 (added explanation of `async_lib.library.sleep` in particular) and #527 (added links to introductory materials about concurrency). Thanks, @vstadnytskyi!
