### ISSUE TITLE
Document supported data types for pvproperty

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#519]
I cannot find a full list of supported data types for pvproperty object. The date types(dtype) are automatically derived from the initial value. Is there a way to specify it? Do I even want to specify it manually? From the documentation I have found examples of how I can create PV:

```
class Server(PVGroup):
    integer = pvproperty(value=1)
    float = pvproperty(value=1.0)
    string = pvproperty(value='1')
    lst = pvproperty(value=[1,2,3.4])
    arr = pvproperty(value=zeros((3,1360,1024)) <- this is PV definition doesn't work , error shown below.

.
.
.

if __name__ == '__main__':
    ioc_options, run_options = ioc_arg_parser(
        default_prefix='simple:',
        desc=dedent(Server.__doc__))
    ioc = Server(**ioc_options)
```
Now, I can see what are data-types of all PVs.
```
In [2]: ioc.integer.data_type
Out[2]: <ChannelType.LONG: 5>
In [3]: ioc.float.data_type
Out[3]: <ChannelType.DOUBLE: 6>
In [4]: ioc.string.data_type
Out[4]: <ChannelType.CHAR: 4>
In [5]: ioc.lst.data_type
Out[5]: <ChannelType.LONG: 5>
```
However, when I tried to create a PV and put a numpy array or dictionary as initial value, I have gotten an error. Using PDB I was able to get access to the list of supported data types.
```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/server/server.py in data_class_from_pvspec(group, pvspec)
   1062         return group.type_map_read_only[pvspec.dtype]
   1063
-> 1064     return group.type_map[pvspec.dtype]
   1065
   1066

KeyError: <class 'numpy.ndarray'>
(Pdb) group.type_map
{<class 'str'>: <class 'caproto.server.server.PvpropertyChar'>,
<class 'bytes'>: <class 'caproto.server.server.PvpropertyByte'>, 
<class 'int'>: <class 'caproto.server.server.PvpropertyInteger'>, 
<class 'float'>: <class'caproto.server.server.PvpropertyDouble'>, 
<class 'bool'>: <class 'caproto.server.server.PvpropertyBoolEnum'>, 
<ChannelType.STRING: 0>: <class 'caproto.server.server.PvpropertyString'>,
<ChannelType.INT: 1>: <class 'caproto.server.server.PvpropertyShort'>,
<ChannelType.LONG: 5>: <class 'caproto.server.server.PvpropertyInteger'>,
<ChannelType.DOUBLE: 6>: <class 'caproto.server.server.PvpropertyDouble'>,
<ChannelType.ENUM: 3>: <class 'caproto.server.server.PvpropertyEnum'>, 
<ChannelType.CHAR: 4>: <class 'caproto.server.server.PvpropertyChar'>}
```
Hence, I have gotten a list of possible data types but there is no explanation what is what and why is there similar entries like: 'str' and 'STRING'.

Ultimately, I want to know how to create a PV that will be a numpy array. Do I need to serialize it and then put as PV?

Also, if I check docstring for pvproperty `help(pvproperty)`, I get the docstring but some fields seem to be missing. Some of them are self-describing but some are not.

```
 |
 |  getter(self, get)
 |
 |  putter(self, put)
 |

.
.
.

 |
 |  shutdown(self, shutdown)
 |
 |  startup(self, startup)

.
.
.

 |  Class methods defined here:
 |
 |  from_pvspec(pvspec) from builtins.type
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  fields  <------ MISSING ONE
 |
 |  record_type
 |      Record type if mocking a record (or None)
```

**Comment by klauer** [comment]
Your criticisms are all very valid of the documentation. I think @tacaswell, @danielballan and I would all like to have more time to improve it - and the entirety of caproto, for that matter.

Regardless, for your specific issue:
* N-dimensional numpy arrays are not supported - only 1D - as channel access has only support for 1D arrays
* caproto works without numpy and has no mapping for its dtypes currently. It must be specified separately.

Noting the above, this should work:  `arr = pvproperty(value=np.zeros(3 * 1360 * 1024), dtype=float)`

The other instance where you'd want to specify a `dtype` to `pvproperty`:
* For an enum (which don't exist as basic Python builtins, in the future this could potentially support `enum.IntEnum`)
* For a data type where you want a smaller storage specification - 16-bit integer - instead of a 32-bit one, which Python has no built-in way of indicating (aside from ctypes, perhaps)

Both of the above would be specified as `dtype=ChannelType.<something>`, which is where those other mapping entries come from.

**Comment by vstadnytskyi** [comment]
> Your criticisms are all very valid of the documentation. I think @tacaswell, @danielballan and I would all like to have more time to improve it - and the entirety of caproto, for that matter.

Hopefully, I will be able to contribute with this and more after I get more understanding of how it is structured.

> Noting the above, this should work: arr = pvproperty(value=np.zeros(3 * 1360 * 1024), dtype=float)

So I can flatten an array. and on the other and I can do something [like this ](https://cars9.uchicago.edu/software/python/pyepics3/arrays.html#example-handling-large-arrays)

```
>>> im_mode = 'RGB'
>>> im_size = (1360, 1024)
>>> img = Image.frombuffer(im_mode, im_size, raw_image,
                            'raw', im_mode, 0, 1)
```

**Comment by klauer** [comment]
Your contributions would be greatly appreciated!

Yes, that's correct - you always work with a flattened array on the server-side (e.g., `await self.arr.write(image.flatten())`) and let the client handle re-shaping.

**Comment by danielballan** [comment]
Yeah, the server API is definitely the biggest hole in the documentation at present. It would be nice to build that out. @klauer, :+1: to supporting `IntEnum` for specifying enums.

**Comment by klauer** [comment]
Where there is a @klauer in the `git blame` there are documentation holes... 😭
