### ISSUE TITLE
"Input/output" - "Device" objects communication

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#521]
I am trying to wtrite a simple IOC that has two objects: main program object and communication object. I cannot figure out how to push an update from the main program to the communication object that uses channel access protocol to update all clients out there.

There is a [random walk](https://caproto.github.io/caproto/iocs.html?highlight=rpc#random-walk) example (see code below for convenience. In this code, the main IOC object does random walk calculations and publishes them to anyone who is listening. The rate of random walk is defined inside of the IO module. At first glance, this is a good structure for a simple IOC. However, this approach intrinsically couples the IO module with a device module.

Let us image, I will have a random walk object that performance these random walk calculations on a timer defined in it. Every time there is a new value, the IO gets notified, and IO updates all clients that are subscribed. This will be more event-driven approach. I see one example similar to what I am asking, but it is for keyboard interrupt, and I just cannot understand how key strokes get passed from outside into the IO. The example is very cryptic to me.

```
#!/usr/bin/env python3
import random
From caproto.server import pvproperty, PVGroup, ioc_arg_parser, run


class RandomWalkIOC(PVGroup):
    dt = pvproperty(value=3.0)
    x = pvproperty(value=0.0)

    @x.startup
    async def x(self, instance, async_lib):
        'Periodically update the value'
        while True:
            # compute next value
            x = self.x.value + 2 * random.random() - 1

            # update the ChannelData instance and notify any subscribers
            await instance.write(value=x)

            # Let the async library wait for the next iteration
            await async_lib.library.sleep(self.dt.value)


if __name__ == '__main__':
    ioc_options, run_options = ioc_arg_parser(
        default_prefix='random_walk:',
        desc='Run an IOC with a random-walking value.')
    ioc = RandomWalkIOC(**ioc_options)
    run(ioc.pvdb, **run_options)
```

Here is my code that works and I can update the PV. However, I do it on a timer that is specified in the IO instead of event driven from the "device" module.

```
#!/usr/bin/env python3
import random
from caproto.server import pvproperty, PVGroup, ioc_arg_parser, run

class RandomWalk(object):

    def __init__(self):
        self.x = 0.0
        self.dt = 3.0
        self.running = True

    def compute_new_x(self,x):
        from numpy import random
        return x + 2 * random.random() - 1

    def run_once(self):
        from numpy import random
        self.x = self.compute_new_x(self.x)
        self.push_to_IO(dict = {'x':self.x})

    def run(self):
        from time import sleep
        while self.running:
            self.run_once()
            sleep(self.dt)

    def start(self):
        from threading import Thread
        thread = Thread(target=self.run)
        thread.daemon = True
        thread.start()
        return thread

    def push_to_IO(self,dict = {}):
        """
        updates the IO PV if it matches the key name in the input dictionary(dict).
        """
        pass

class RandomWalkIO(PVGroup):
    dt = pvproperty(value=3.0)
    x = pvproperty(value=0.0,precision = 3)

    @x.startup
    async def x(self, instance, async_lib):
        'Periodically update the value'
        while True:
            # compute next value

            # update the ChannelData instance and notify any subscribers
            await instance.write(value=device.x)

            # Let the async library wait for the next iteration
            await async_lib.library.sleep(self.dt.value)


device = RandomWalk()
device.start()

if __name__ == '__main__':
    from pdb import pm
    ioc_options, run_options = ioc_arg_parser(
        default_prefix='random_walk:',
        desc='Run an IOC with a random-walking value.')
    ioc = RandomWalkIO(**ioc_options)
    run(ioc.pvdb, **run_options)
```

**Comment by vstadnytskyi** [comment]
It was easier than I thought. Here is my simple example. I still don't get the use of `new_value_callback` but I got it to work. 

```
#!/usr/bin/env python3
import termios
import fcntl
import sys
import os
import threading
import atexit
from time import time,sleep
from datetime import datetime

from caproto.server import pvproperty, PVGroup, ioc_arg_parser, run


def start_io_interrupt_monitor(new_value_callback):
    '''
    This function monitors the terminal it was run in for keystrokes.
    On each keystroke, it calls new_value_callback with the given keystroke.

    This is used to simulate the concept of an I/O Interrupt-style signal from
    the EPICS world. Those signals depend on hardware to tell EPICS when new
    values are available to be read by way of interrupts - whereas we use
    callbacks here.
    '''
    while True:
        new_value_callback(time())
        sleep(1)


class IOInterruptIOC(PVGroup):
    t1 = pvproperty(value='')
    t2 = pvproperty(value='')

    # NOTE the decorator used here:
    @t1.startup
    async def t1(self, instance, async_lib):
        # This method will be called when the server starts up.
        print('* keypress method called at server startup')
        queue = async_lib.ThreadsafeQueue()

        # Start a separate thread that monitors keyboard input, telling it to
        # put new values into our async-friendly queue
        thread = threading.Thread(target=start_io_interrupt_monitor,
                                  daemon=True,
                                  kwargs=dict(new_value_callback=queue.put))
        thread.start()

        # Loop and grab items from the queue one at a time
        while True:
            value = await queue.async_get()
            date_time = datetime.fromtimestamp(value)
            t = date_time.strftime("%m/%d/%Y, %H:%M:%S")
            print(f'Saw new value on async side: {value!r}')

            # Propagate the keypress to the EPICS PV, triggering any monitors
            # along the way
            await self.t1.write(t)

if __name__ == '__main__':
    ioc_options, run_options = ioc_arg_parser(
        default_prefix='io_device:',
        desc='Run an IOC that updates via I/O interrupt on key-press events.')

    ioc = IOInterruptIOC(**ioc_options)
    run(ioc.pvdb, **run_options)
```

**Comment by danielballan** [comment]
I'll take a stab at trying to clarify `new_value_callback`. Since `new_value_callback` is assigned to `queue.put`, calling `new_value_callback(thing)` puts `thing` into the queue. The IOC receives it and publishes an update to subscribe clients. I'm not sure if that addresses your question.

Reading your initial post, it sounds like the two "worker thread" examples might be useful to study. Like your example above, a worker (which would presumably do device communication) runs on a thread and communicates back to the IOC.

In the [`worker_thread_pc`](https://github.com/caproto/caproto/blob/master/caproto/ioc_examples/worker_thread_pc.py) example, there is just one PV. The worker receives some command from the IOC (i.e. some desired set point) and confirms when it is done. See #508 for example usage and more remarks. Be warned that this example uses a feature that is in the `master` branch now but not yet available in a released version of caproto. It is [soon to be released](https://github.com/caproto/caproto/pull/522) in caproto v0.4.1.

In the [`worker_thread`](https://github.com/caproto/caproto/blob/master/caproto/ioc_examples/worker_thread.py) example, there are two PVs. The worker receives a command the same as before, but it also has the opportunity to send a _response_ to the IOC with some content, such as a readback value. This is different from the first example because the first example only allows the worker to signal _timing_ ("I'm done") not a value ("I'm done and here's a result.")  See #511 for example usage and more remarks.
