### ISSUE TITLE
Requesting timestamp with sync or thread client

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#524]
I cannot figure out how to get a timestamp(when PV was published) together with the value of a PV. Is there a way to get the timestamp?

threaded client
```
from caproto.threading.client import Context
default_prefix='io_device:'
ctx = Context()
img,t1,t2 = ctx.get_pvs(default_prefix+'image',default_prefix+'t1',default_prefix+'t2')
t1.read().data[0] # will give me data from the PV
```
 Sync client
```
from caproto.sync.client import read
t1 = read('io_device:t1')
```

**Comment by danielballan** [comment]
There is, but it could be documented more prominently than it is. I have attempted to remedy that in https://github.com/caproto/caproto/pull/526 just now. Would you take a look at that and suggest any clarifications / improvements that could be made?

**Comment by danielballan** [comment]
My request for comment was premature---there were a bunch of typos. Just pushed a new commit to that PR to fix them. I hope you didn't lose to much time trying to get the typo-ridden version to work.

**Comment by vstadnytskyi** [comment]
> My request for comment was premature---there were a bunch of typos. Just pushed a new commit to that PR to fix them. I hope you didn't lose to much time trying to get the typo-ridden version to work.

I haven't worked on this yet. I will look at this later. I want to figure out how to get timestamp in my code first.

**Comment by danielballan** [comment]
Riffing on your example, I think you want:


```py
from caproto.threading.client import Context
default_prefix='io_device:'
ctx = Context()
img,t1,t2 = ctx.get_pvs(default_prefix+'image',default_prefix+'t1',default_prefix+'t2')
t1.read().metadata.timestamp
# or, if you prefer a datetime object
t1.read(data_type='time').metadata.stamp.as_datetime()
```

```py
from caproto.sync.client import read
t1 = read('io_device:t1', data_type='time').metadata.timestamp
# or, if you prefer a datetime object
t1 = read('io_device:t1', data_type='time').metadata.stamp.as_datetime()
```

**Comment by vstadnytskyi** [comment]
Here is what I found.

The IOC on the server side might get busy servicing a read request from a client and it can be up to 80 ms delay in time between when "device" submitted publish a request and it was served by the server IOC.

Server and the client are on the different machines
![DEA71706-60A3-422F-8008-DC2FEB3CE082](https://user-images.githubusercontent.com/29989124/66499742-63ac4280-ea8e-11e9-8383-dffcd60cf2f1.png)

 
![86F7620D-1295-4CBE-8BBB-BBDBC46609F9](https://user-images.githubusercontent.com/29989124/66499769-6f980480-ea8e-11e9-8ec8-d61844a5dd4a.png)

**Comment by vstadnytskyi** [comment]
> My request for comment was premature---there were a bunch of typos. Just pushed a new commit to that PR to fix them. I hope you didn't lose to much time trying to get the typo-ridden version to work.

I guess we can close this issue then.
