### ISSUE TITLE
caproto server interface with pyepics

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#525]
I have created [my repository](https://github.com/vstadnytskyi/caproto-sandbox/issues), where I explore caproto. I am having an issue with caproto server interfacing pyepics, and I don't understand what is going on. 

Since I am not sure if it is related to caproto or pyepics, I have created an [issue](https://github.com/vstadnytskyi/caproto-sandbox/issues/3) in my repository. 

would you prefer me to copy the entire text here, or is it fine to post a link here?

**Comment by danielballan** [comment]
The link is fine, thanks!

**Comment by danielballan** [comment]
Fixed by #529, as noted in the linked issue.
