### ISSUE TITLE
mock records not compliant to 'real' EPICS records

### ISSUE THREAD

**Issue by baldwinb** [caproto/caproto#537]
I have found that reading all of the fields of a mock record show the following problems:
1) a read of a string typically returns a char array/waveform (when linux cli expects string)
2) some PVs fail read of value, or read of enums

For more information:

1) 
A change is needed to allow:
- return of string PVs as "DBR_STRING" type when caget from cli without appending "$"
- return of char array "DBR_CHAR" type when caget from cli when appending "$"

Appending "$" to the PV should return a char array. Typically this is used from linux CLI: 
caget -S "PV$"
so that the char array is converted to a string, and this has no length requirements. Caproto currently returns char array for both.

Refer to pull request from https://github.com/baldwinb/caproto/tree/compliance_check , which adds compliance test highlighting other issues that can be observed when reading all pvs of a mock record from linux cli, or common epics gui tools. The pull request also changes the records.py file to use string type instead of char array (which is how EPICs normally works). However, modifying records.py to use strings means it now returns strings even when appending "$".

2)
Other miscellaneous problems are also evident when running "pytest test_ai_compliance.py" that need to be fixed (but is not clear to me how to do this).  Such as: problems reading ADEL field, and enum of STAT field.

**Comment by klauer** [comment]
Fixing the ADEL issue with: https://github.com/klauer/caproto/commit/4ea0d6cb1459b9cf5a7b9485bcd53e19d9487d55

**Comment by klauer** [comment]
I think we're largely there with regards to compliance. Thanks for the push to get this going @baldwinb.

Let's open up new issues for specific records/fields as we find them.
