### ISSUE TITLE
Problems with reseting PV after servicing a button call from a GUI

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#555]
I have been fighting with caproto for some time. Here is what I am trying to do.

I have a GUI and a motor IOC. I have a jog button that performs jog of a motor (moving plus and minus certain value). The button submits 1.0 to "motor.jog" and disables itself while "motor.jog" is equal to 1. When motor IOC receives the value 1.0 it does the jog and I want it to reset itself back to 0. This will enable a button.

``` python
class Server(PVGroup):
    jog = pvproperty(value=0.0)

   
    @jog.putter
    async def jog(self, instance, value):
        print(f"Server: {'jog'} Got 'put' request from outside: new value is {value} and type {type(value)}")
        if float(value) == 1.0:
             print('performing jog')
       if self.jog.value == 0.0 and float(value) == 1.0:
            print('reseting jog value to 0')
            await self.jog.write(float(0.0))
    @jog.getter
    async def jog(self, instance):
        pass
```

```
[I 12:06:08.335          common:  967] Connected to new client at 1.54.161.88:50142 (total: 1).
Server: jog Got 'put' request from outside: new value is 1.0 and type <class 'numpy.float64'>
performing jog'
reseting jog value to 0
Server: jog Got 'put' request from outside: new value is 0.0 and type <class 'float'>
```

If I access the PV from another client I get 1 and my button is still disabled. 
<img width="312" alt="image" src="https://user-images.githubusercontent.com/29989124/73613045-5aa02d80-45b7-11ea-9559-9e0afb3cd36c.png">

What am I doing wrong and is there a better way to do this?

**Comment by vstadnytskyi** [comment]
It looks like I have to go via ThreadSaveQueue

``` python
@running.startup
    async def running(self, instance, async_lib):
        print('* request method called at server startup @start.startup')
        self.put_queue = async_lib.ThreadsafeQueue()
        self.get_queue = async_lib.ThreadsafeQueue()
        while True:
            if True: #self.put_queue is not None:
                entry = await self.put_queue.async_get()
                print(f'Async Put Queue: Got put request from the device: {entry}')
                pv = entry['pv']
                value = entry['value']
                if pv == 'jog':
                    await self.jog.write(value)
            else:
                await async_lib.library.sleep(0.1)
```

and then I can reset my PV this way.
``` python
if self.jog.value != float(value):
            await self.put_queue.async_put({'pv':'jog','value':0.0})
```

**Comment by danielballan** [comment]
If the desired behavior is

1. A GUI button is enabled.
2. Clicking the button submits a request to the IOC and disables the button.
3. Once the request is processed, the button is enabled again.

then you might consider doing this entirely on the client side. Assuming we have `pv`, a `caproto.threading.client.PV` instance, and the functions `disable_button` and `enable_button`:

```py
def on_button_press():
    disable_button()
    pv.write(..., callback=enable_button)
```

will ask the server to send a `WriteNotifyResponse` write is complete and it will call `enable_button(response)` at that time on a background thread.

**Comment by vstadnytskyi** [comment]
@danielballan I am using build-in pyepics buttons. There I can specify which PV and its' value disables the button. If I use your proposed approach, I will need to have this code in all clients. If I do it on the server-side, then it is seamless for a front end user. I can imagine using multiple PVs that trigger different actions on the server-side that behaves this way. I submit 1, server services the call and returns 0 when it is done.

**Comment by danielballan** [comment]
I see. I don't know the details of pyepics buttons. In general, I like relying on "put completion" (running a callback on `WriteNotifyResponse`) whenever I can because it keeps the logic self-contained to one PV, and it's specific about _which_ action has been completed. I don't personally find the client code associated with put completion any more complex than the client code required to manage watching for some PV to flip between 1 and 0. But again, lacking the details of how pyepics buttons work, my intuition might not apply here. Glad you found something that works!

**Comment by danielballan** [comment]
This example (still under review/revision) might be of interest as well: https://github.com/caproto/caproto/pull/467

where our "trigger" is analogous to your "jog". One of the key concerns here is to ensure that if there are _multiple_ clients (two GUIs, or a GUI and someone using `caput`) that they don't step on each other. The `no_reentry` and `contextvars` stuff is related to that.

**Comment by tacaswell** [comment]
A critical detail is that the `write` where you are setting the PV to 1 happens after `putter` returns so instead of doing 0 -> 1 -> 0 you are doing 0 -> 0 -> 1.  The `no_reentry` is what lets you force the write (to the "high" value) to happen first  without triggering an infinite recursion.

**Comment by vstadnytskyi** [comment]
> This example (still under review/revision) might be of interest as well: #467 -- specifically the file https://github.com/caproto/caproto/pull/467/files#diff-28dc1873127fce12e46cb77692e4a6e5
> 
> where our "trigger" is analogous to your "jog". One of the key concerns here is to ensure that if there are _multiple_ clients (two GUIs, or a GUI and someone using `caput`) that they don't step on each other. The `no_reentry` and `contextvars` stuff is related to that.

Do I understand it right?  This noreentry decorator will allow execution putter if the put comes from outside(client) but will not execute putter if it is internal call?

**Comment by tacaswell** [comment]
> Do I understand it right? This no_reentry decorator will allow execution putter if the put comes from outside(client) but will not execute putter if it is internal call?

Yes

**Comment by klauer** [comment]
You may have found that the `no_reentry` decorator is broken in implementing this - I did in a separate IOC: https://github.com/caproto/caproto/issues/625

The general idea and suggestion provided here is correct, however. Please re-open this issue if you want to continue the discussion.
