### ISSUE TITLE
KeyError: <ChannelType.GR_ENUM: 24>

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#556]
I can create an ENUM type PV. However, when I transfer it to a client I get only 25 characters out of it. 

```
from caproto import ChannelType
choices = pvproperty(value=' ',enum_strings=enum_strings , dtype=ChannelType.ENUM)
```

I have tried some other type from the list (see below) but some of them give me errors.

```
STRING = 0
INT = 1
FLOAT = 2
ENUM = 3
CHAR = 4
LONG = 5
DOUBLE = 6
STS_STRING = 7
STS_INT = 8
STS_FLOAT = 9
STS_ENUM = 10
STS_CHAR = 11
STS_LONG = 12
STS_DOUBLE = 13
TIME_STRING = 14
TIME_INT = 15
TIME_FLOAT = 16
TIME_ENUM = 17
TIME_CHAR = 18
TIME_LONG = 19
TIME_DOUBLE = 20
GR_STRING = 21
GR_INT = 22
GR_FLOAT = 23
GR_ENUM = 24
GR_CHAR = 25
GR_LONG = 26
GR_DOUBLE = 27
CTRL_STRING = 28
CTRL_INT = 29
CTRL_FLOAT = 30
CTRL_ENUM = 31
CTRL_CHAR = 32
CTRL_LONG = 33
CTRL_DOUBLE = 34
STSACK_STRING = 37
CLASS_NAME = 38
```

Here is an example of an error I get

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~//Software/caproto-sandbox/caproto_sandbox/example_1_server.py in <module>
    128         self.y_val_monitor.write(new)

    129
--> 130 class Server(PVGroup):
    131     io_put_queue = None
    132

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/server/server.py in __new__(metacls, name, bases, dct)
   1041                 # class, so it doesn't bite us on instantiation
   1042
-> 1043                 prop_cls = data_class_from_pvspec(group=cls, pvspec=pvspec)
   1044                 if not hasattr(prop_cls, '_valid_init_kw'):
   1045                     # TODO this should be generated elsewhere

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/server/server.py in data_class_from_pvspec(group, pvspe
c)
   1062         return group.type_map_read_only[pvspec.dtype]
   1063
-> 1064     return group.type_map[pvspec.dtype]
   1065
  1065

KeyError: <ChannelType.GR_ENUM: 24>
```

**Comment by klauer** [comment]
The enum string length limitation is due to the underlying channel access protocol and is not a bug: https://github.com/caproto/caproto/blob/1a7356487fd930cb6dee6c26f1ce1f117cd87c95/caproto/_constants.py#L14

For `pvproperty`, you should not be creating anything but basic types - which is why that's failing. As caproto manages the metadata necessary to send along the status, graphic, timestamp, and control variants, valid options are as follows:
```
STRING = 0
INT = 1
FLOAT = 2
ENUM = 3
CHAR = 4
LONG = 5
DOUBLE = 6
```

**Comment by vstadnytskyi** [comment]
> The enum string length limitation is due to the underlying channel access protocol and is not a bug:
> 
> https://github.com/caproto/caproto/blob/1a7356487fd930cb6dee6c26f1ce1f117cd87c95/caproto/_constants.py#L14
> 
> For `pvproperty`, you should not be creating anything but basic types - which is why that's failing. As caproto manages the metadata necessary to send along the status, graphic, timestamp, and control variants, valid options are as follows:
> 
> ```
> STRING = 0
> INT = 1
> FLOAT = 2
> ENUM = 3
> CHAR = 4
> LONG = 5
> DOUBLE = 6
> ```

I have found a list of types and I assumed that all of them are viable options. What is the rest in the list?

**Comment by danielballan** [comment]
The rest in the list in variations on these basic types that add metadata (timestamps, various limits, etc.).
