### ISSUE TITLE
caproto.bcast:Beacon anomaly

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#561]
I am getting a lot(few every second) of INFO statements as shown below in a range of IP addresses. I have see around 11 different IP addresses including ip-addresses I am not talking to in my caproto server.

`INFO:caproto.bcast:Beacon anomaly: 1.54.161.3:5064 may have restarted.`

Why would I get all of these INFO statements? They completely swamp my terminal output and I cannot see information printed by my code.

**Comment by danielballan** [comment]
INFO-level statements should not be shown by default. Have you dialed up the log verbosity somewhere in your code?

**Comment by danielballan** [comment]
The cause of this specific message, by the way, indicates that the UDP beacons sent out by the server have started arriving faster, which indicates that the server may have crashed and restarted or else something about the network is causing them to fail to arrive reliably.

I haven’t seen this message frequently in action so I expect that they are reporting correctly, but it might be worth checking the code paths around that log message to check that they look right.

**Comment by vstadnytskyi** [comment]
> INFO-level statements should not be shown by default. Have you dialed up the log verbosity somewhere in your code?

I have searched for the word 'log' in my code. I have only one line related to logging.

`from logging import debug, info, warning, error`

**Comment by danielballan** [comment]
It looks like you also set up logging handlers [here](https://github.com/vstadnytskyi/caproto-sandbox/blob/3d1ee41bf89b47723d4533941163026357b72e28/system_level_io_template.py#L76-L77) and [here](https://github.com/vstadnytskyi/caproto-sandbox/blob/91f63e147161efe0d2540c635300cbfb811f08b6/caproto_sandbox/image_io.py#L42-L43) that capture DEBUG-level log messages to a file. That sends messages to the stdout as well, as illustrated here:

```py
In [3]: logging.basicConfig(filename='/tmp/caproto-logging-test.log', level='DEBUG')                                                                                                          

In [4]: from caproto.threading.client import Context                                                                                                                                          
DEBUG:caproto:Backend 'array' registered
DEBUG:caproto:Backend 'numpy' registered
DEBUG:caproto:Selecting backend: 'numpy'

In [5]: ctx = Context()                                                                                                                                                                       
DEBUG:caproto.bcast:Broadcaster command loop is running.
DEBUG:caproto.bcast:Broadcaster check for unresponsive servers loop is running.
DEBUG:caproto.bcast:RepeaterRegisterRequest(client_address='0.0.0.0')
DEBUG:caproto.bcast:1 commands 16B
DEBUG:caproto.bcast:1 commands 16B
DEBUG:caproto.bcast:1 commands 16B
DEBUG:caproto.bcast:1 commands 16B
DEBUG:caproto.bcast:1 commands 16B
DEBUG:caproto.bcast:Broadcaster search-retry thread has started.
DEBUG:caproto.ctx:Context search-results processing loop has started.
```

If you want DEBUG-level messages from everything _except_ caproto, you could raise the threshold for caproto specifically like so:

```py
In [1]: import logging                                                                                                                                                                        

In [2]: logging.basicConfig(filename='/tmp/caproto-logging-test.log', level='DEBUG')                                                                                                          

In [3]: logging.getLogger('caproto').setLevel('WARNING')

# now we won't see any log messages here....                                                                                                                                      

In [4]: from caproto.threading.client import Context                                                                                                                                          

In [5]: ctx = Context()
```

See also of course https://caproto.github.io/caproto/loggers.html for some useful resources around Python logging in general and caproto logging in particular.

**Comment by vstadnytskyi** [comment]
> It looks like you also set up logging handlers [here](https://github.com/vstadnytskyi/caproto-sandbox/blob/3d1ee41bf89b47723d4533941163026357b72e28/system_level_io_template.py#L76-L77) and [here](https://github.com/vstadnytskyi/caproto-sandbox/blob/91f63e147161efe0d2540c635300cbfb811f08b6/caproto_sandbox/image_io.py#L42-L43) that capture DEBUG-level log messages to a file. 

Those are two old examples. The one I am running right now doesn't have any of that. I just tried to comment out  `#from logging import debug, info, warning, error` and it fixed the problem. So somehow the import of` debug, info, warning, error` turns it on.

**Comment by danielballan** [comment]
Very surprising behavior. I think this may be a Python logging thing, not a caproto-specific thing. Please feel free to reopen the issue if you find something that we should change in caproto to help make this work as expected.
