### ISSUE TITLE
ValueError: Passing `reuse_address=True` is no longer supported, as the usage of SO_REUSEPORT in UDP poses a significant security concern.

### ISSUE THREAD

**Issue by jklynch** [caproto/caproto#562]
While running the NSLS-II-TES profile_collection in CI the following ValueError occurred:

ValueError: Passing `reuse_address=True` is no longer supported, as the usage of SO_REUSEPORT in UDP poses a significant security concern.

The full error report is available [here](https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=279&view=logs&j=16956ce3-ed22-53ee-0d4a-83af89f6a95f&t=bb1ce8cf-ce47-5eb4-63bd-c282c6cebb46&l=382).

**Comment by danielballan** [comment]
Python made a breaking changes in all its currently-maintained releases. We address it in caproto 0.4.3. See https://caproto.github.io/caproto/release-notes.html#v0-4-3-2020-01-29.

**Comment by danielballan** [comment]
The build log shows it ran with caproto v0.3.4. Perhaps caproto is being pinned to below 0.4 to avoid a regression affecting Windows. Fortunately, that was addressed in 0.4.3 as well so it should be safe to upgrade.
