### ISSUE TITLE
EPICS_CA_AUTO_ADDR_LIST=YES and EPICS_CA_ADDR_LIST settings

### ISSUE THREAD

**Issue by klauer** [caproto/caproto#590]
epics-base channel access takes the following:
```
EPICS_CA_AUTO_ADDR_LIST=YES
EPICS_CA_ADDR_LIST=1.2.3.4 5.6.7.8
```

And uses the automatic address list _in addition to_ those specified in `EPICS_CA_ADDR_LIST`.

caproto warns about the additional addresses, assuming they were configured in error.

**Comment by danielballan** [comment]
This explains a lot!
