### ISSUE TITLE
[Question] Access documentation by realease, instead of only latest tag.

### ISSUE THREAD

**Issue by gohierf** [caproto/caproto#594]
Using pip I installed caproto v0.4.4.

However I can only find the documentation for `0.5.0a1+204.gc6400f3.dirty` version. Neither on https://nsls-ii.github.io/caproto/ nor https://caproto.github.io/caproto/, can find a way to choose the release version I'm interested in.

This has caused me trouble with `mock_record` now being called `record` in the docs, and callback functions attatched to a subscribtion being provided only one argument instead of two (only `response`, no `sub`).

Could you tell me the way to get access to previous release or tags, please ?

Also I'm surprised that I didn't get any exception raised when my callback function failled because I defined with two arguments. The function called just did nothing. Maybe this is sorted in the next version ?

**Comment by danielballan** [comment]
> Could you tell me the way to get access to previous release or tags, please ?

You'll have to build it locally.

```
pip install -r docs-requirements.txt
make -C doc html
```

I agree this is a problem. Until recently there has been no open-source tool for publishing multiple versions, but there are ways to do it.

> Also I'm surprised that I didn't get any exception raised when my callback function failled because I defined with two arguments. The function called just did nothing. Maybe this is sorted in the next version?

I expect that it failed on a background thread. Perhaps we can make it log the failure more "loudly".

**Comment by danielballan** [comment]
Following up on

> Until recently there has been no open-source tool for publishing multiple versions, but there are ways to do it.

This is the tool that we should use to do this, since we publish our docs with doctr: https://github.com/goerz/doctr_versions_menu

**Comment by klauer** [comment]
Old documentation such as v0.4.4 is now available: https://caproto.github.io/caproto/v0.4.4/

Please let us know if you find issues with it.
