### ISSUE TITLE
Revisiting caproto.threading.client.PV.__init__

### ISSUE THREAD

**Issue by danielballan** [caproto/caproto#609]
Tangential to #607:

I'm not sure why `PV.__init__`, which is internal, needs to take in `connection_state_callback` and `access_right_callback`. The public methods `PV.connection_callback.add_callback` and `PV.access_rights_callback.add_callback` can be called after `__init__` time, and will still be run even if registration happens after the relevant event (e.g when connection happens). And unlike `__init__`, they expose the possibility of registering multiple callbacks.

Would anyone be opposed to removing those parameters from `PV.__init__`? The public way to initialize `PV` is via `Context.get_pvs` and `PV.__init__` has always been documented as internal, not to be called by the user.

**Comment by tacaswell** [comment]
On one hand I think this is a compelling point and in abstract pushing the callback registration out of the init method is correct, on the other hand the current state is not that harmful and I'm skeptical of code change for the sake of code change.

I'm aggressively neutral on this :shrug: .
