### ISSUE TITLE
Examples are too clever

### ISSUE THREAD

**Issue by klauer** [caproto/caproto#616]
The example IOCs leave a lot to be desired - many were written to test the server functionality in place of a proper test suite.

These should be removed or cleaned and simplified.

**Comment by danielballan** [comment]
Agreed that these serve a range of purposes now. Maybe some could be moved under `tests/`.

**Comment by danielballan** [comment]
I propose:

```
caproto/
    ioc_examples
        simple.py
        random_walk.py
        ...
        too_clever/
            caproto_to_ophyd.py
            dynamic_pygroups.py
            ...
        pathological/
            defaultdict_server.py
            spoof_beamline.py
            reading_counter.py
            ...
        hardware_specific/
            barcode.py
```

**Comment by klauer** [comment]
Sounds about right

_pathological_ 😁

**Comment by klauer** [comment]
@danielballan have desire/time to rearrange/prune the examples?

Anything pruned could potentially go in a separate dumping ground repository, perhaps.

**Comment by danielballan** [comment]
Yeah, was thinking about this again over the weekend. Will do today. I'm inclined to rearrange the directory structure and then move things into other repos in separate PRs. I love the new cookiecutter, seems like it would be good for this.

**Comment by klauer** [comment]
@danielballan great - and glad to hear about the cookiecutter 👍
