### ISSUE TITLE
PVGroup documentation not rendering in caproto docs

### ISSUE THREAD

**Issue by klauer** [caproto/caproto#665]
It appears to not be finding the templates...

**Comment by klauer** [comment]
Well, I'm at a loss here - this works so easily locally, but fails silently in caproto CI and [downstream IOC CI](https://pcdshub.github.io/fluke_985/master/ioc/fluke_985.ioc.Fluke985Base.html).

**Comment by klauer** [comment]
TIL https://packaging.python.org/guides/distributing-packages-using-setuptools/#manifest-in

(why is Python packaging so painful?)

**Comment by klauer** [comment]
Closed by #667

e.g., https://caproto.github.io/caproto/master/generated/caproto.ioc_examples.mini_beamline.MiniBeamline.html

**Comment by danielballan** [comment]
This looks so good @klauer! Very cool.
