### ISSUE TITLE
CI: nuke epics-on-travis, rely on softIoc only

### ISSUE THREAD

**Issue by klauer** [caproto/caproto#676]
Protocol-wise, there's no difference between a motorSim IOC containing motor records and an epics-base `softIoc` with analog input/output records.

We have built-in support for per-test running of a background `softIoc` that doesn't require any previous setup (other than having epics-base available, of course), and we should use it.

This should increase reliability of CI jobs.

**Comment by klauer** [comment]
Looks like `epics-base` on conda-forge does what we need, but switching to conda will slow down CI in building the environment.

Could also build epics-base ourselves and just cache it, which isn't so difficult to do - it's just fiddly with travis/azure.

**Comment by tacaswell** [comment]
I wonder if we can make better use of the tarvis/azure cache by caching a snapshot of the solve (I am blanking on the right names, but there is a way to get a list of packages such that conda won't try to re-solve, it will trust you) and make sure we cache the downloaded tarballs.

**Comment by klauer** [comment]
@tacaswell would be great if possible. Are you aware of any projects using that method?

**Comment by tacaswell** [comment]
no, not off the top of my head.
