### ISSUE TITLE
pyepics_compat: char_value and enum_str not working on mbbi

### ISSUE THREAD

**Issue by spreiter** [caproto/caproto#682]
While trying to access PVs created by a softIOC based on EPICS 3.15, the attributes `char_value` and `enum_str` show wrong values. The `get(as_string=True)` method works nicely.

char_value
----------
The **char_value** attribute returns `None` for mbbi/mbbo records, even though names are available for the states.

enum_str
--------
The **enum_str** attribute shows a list of names, but does not take into account the integer representation of the state name. In case state0 and state3 are set, only two entries are in the returned list, but four would be more representative. In pyepics, state1 and state2 are displayed as `''` empty strings.

**Comment by klauer** [comment]
Thanks for reporting these incompatibilities, @spreiter - and sorry for the late reply!

We definitely would like to fix these to get better feature parity with pyepics PV instances.
