### ISSUE TITLE
Trim b'\x00' from results of PV.read(data_type=ChannelType.STRING)

### ISSUE THREAD

**Issue by jklynch** [caproto/caproto#684]
Would it make sense to trim the `b'\x00'` padding before returning strings from  `PV.read(data_type=ChannelType.STRING)`?

For example, when I read a PV that I expect to return `"No"` like this:

```python
file_path_exists_pv.read(data_type=ChannelType.STRING).data.tobytes().decode()
```

I get `"No\x00\x00\x...0\x00\x00\x00"`. But I just want the `"No"`.

**Comment by klauer** [comment]
I think this may have been on an old version. `DbrStringArray` (introduced in f869df9963160df43af0f61f37f3fc5da2e5c78c) handles conversion of scalar strings and arrays of strings, with special handling to trim null terminators. 

Checking the above in code with `caproto/ioc_examples/scalars_and_arrays.py`:
```python
from caproto.threading.client import Context
from caproto import ChannelType

ctx = Context()
pv, = ctx.get_pvs('arr:scalar_string')
print("pv.read().data=", pv.read(data_type=ChannelType.STRING).data)
print("pv.read().data[0].decode('ascii')=", pv.read(data_type=ChannelType.STRING).data[0].decode('ascii'))
```

Yields
```
pv.read().data= [b'string1']
pv.read().data[0].decode('ascii')= string1
```

**Comment by klauer** [comment]
Closing this for now. Please reopen if you run into this again on a recent version.
