### ISSUE TITLE
Request: Warn/raise if setting both .scan and .startup

### ISSUE THREAD

**Issue by ronpandolfi** [caproto/caproto#691]
I ran into an issue when trying to utilize both `.scan` and `.startup`; only one can be used at a time. This is noted in the docstring of `.scan`, but not `.startup`. It would be nice to give feedback when using these incorrectly (simultaneously).

**Comment by danielballan** [comment]
Any interest in tackling this one @ronpandolfi. It seems it might be a "good first issue" for caproto server development/maintenance.

**Comment by ronpandolfi** [comment]
@danielballan Do you mind if I raise ValueError in this situation?

**Comment by danielballan** [comment]
Seems better than the status quo of silently failing for sure. Ideally we could compose them, but I’d need to think about what implications that might have. Happy to merge #691 as a step forward.
