### ISSUE TITLE
Failure to raise DisconnectedCircuit

### ISSUE THREAD

**Issue by danielballan** [caproto/caproto#696]
@mrakitin reported seeing error like this on [the CI for a beamline profile where caproto is used for simulated hardware](https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=1270&view=logs&j=f9902ac2-07f5-5f38-a83c-04fda0b3ca53&t=f8d34d36-0f4a-596c-c42f-6c04499af201&l=978).
```

[I 21:09:37.378       common: 1094] Disconnected from client at 127.0.0.1:32942 (total: 0).
[I 21:09:37.378       common: 1079] Connected to new client at 127.0.0.1:32944 (total: 1).
[I 21:09:37.511       common: 1094] Disconnected from client at 127.0.0.1:32944 (total: 0).
[I 21:09:37.513       common: 1079] Connected to new client at 127.0.0.1:32946 (total: 1).
[I 21:09:37.651       common: 1079] Connected to new client at 127.0.0.1:32948 (total: 2).
Task exception was never retrieved
future: <Task finished coro=<VirtualCircuit.command_queue_loop() done, defined at /home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/caproto/server/common.py:261> exception=BrokenPipeError(32, 'Broken pipe')>
Traceback (most recent call last):
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/caproto/server/common.py", line 285, in command_queue_loop
    await self.send(*response)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/caproto/asyncio/server.py", line 86, in send
    b''.join(buffers_to_send))
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/asyncio/selector_events.py", line 433, in sock_sendall
    return await fut
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/asyncio/selector_events.py", line 442, in _sock_sendall
    n = sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```

I think that in this loop:

https://github.com/caproto/caproto/blob/49f9f2865a3fa0bd8436ceba03f8a15ece724b81/caproto/server/common.py#L280-L290

we should expect

https://github.com/caproto/caproto/blob/49f9f2865a3fa0bd8436ceba03f8a15ece724b81/caproto/server/common.py#L285

to raise `DisconnectedCircuit` and thereby terminate the `command_queue_loop` for this circuit. Instead, it's leaking a `BrokenPipeError` exception, which we do not expect. The fix would be to catch the `BrokenPipeError` here

https://github.com/caproto/caproto/blob/49f9f2865a3fa0bd8436ceba03f8a15ece724b81/caproto/asyncio/server.py#L85-L86

and reraise a `DisconnectCircuit` from it.

**Comment by klauer** [comment]
Maybe catch the more general base class `ConnectionError`? https://docs.python.org/3/library/exceptions.html#ConnectionError
