### ISSUE TITLE
INFO:caproto.circ:High load

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#703]
I have a camera with 12.3Mpixels and 4096x3000 resolution. The 12bit data is packaged as 8bit flatten numpy array. I can stream these images at 15.6 FPS at 18432000 bytes per image. This gives me 274.2 MB/sec data transfer ( I have 10GBit network in the lab). 

I have noticed I am getting this message.

`INFO:caproto.circ:High load. Batched 2 commands (36864048B) with 0.0241s latency.`

What does it mean? Does it mean I am sending too much data?

My caproto server went fine for around 20 minutes and then I saw these messages("High Load" just before it crashed. I am using caproto logging to see messages.

Here are the last entries in the logger before it suddenly stopped.
```
INFO:caproto.circ:High load. Batched 2 commands (36864048B) with 0.0241s latency.
DEBUG:caproto.circ:EventAddResponse(data=array([12317.]), data_type=<ChannelType.DOUBLE: 6>, data_count=1, status=CAStatusCode(name='ECA_NORMAL', code=0, code_with_severity=1, severity=<CASeverity.SUCCESS: 1>, success=1, defunct=False, description='Normal successful completion'), subscriptionid=1, metadata=None)
DEBUG:caproto.circ:EventAddResponse(data=array([20, 48,  1, ..., 18, 48,  1], dtype=int16), data_type=<ChannelType.INT: 1>, data_count=18432000, status=CAStatusCode(name='ECA_NORMAL', code=0, code_with_severity=1, severity=<CASeverity.SUCCESS: 1>, success=1, defunct=False, description='Normal successful completion'), subscriptionid=0, metadata=None)
DEBUG:caproto.bcast:VersionRequest(priority=10, version=11)
DEBUG:caproto.bcast:SearchRequest(name='DM34_CAMERA:HITS.RBV', cid=10, version=11, reply=5)
DEBUG:caproto.bcast:VersionRequest(priority=10, version=11)
DEBUG:caproto.bcast:SearchRequest(name='DM4_CAMERA:HITS.RBV', cid=11, version=11, reply=5)
DEBUG:caproto.bcast:VersionRequest(priority=10, version=11)
DEBUG:caproto.bcast:SearchRequest(name='BIOCARS:SERVERS.PICO1.BIOCARS.13.RUNNING', cid=1, version=11, reply=5)
DEBUG:caproto.circ:EventAddResponse(data=array([12318.]), data_type=<ChannelType.DOUBLE: 6>, data_count=1, status=CAStatusCode(name='ECA_NORMAL', code=0, code_with_severity=1, severity=<CASeverity.SUCCESS: 1>, success=1, defunct=False, description='Normal successful completion'), subscriptionid=1, metadata=None)
DEBUG:caproto.bcast:VersionRequest(priority=10, version=11)
DEBUG:caproto.bcast:SearchRequest(name='BIOCARS:SERVERS.PICO1.BIOCARS.18.RUNNING', cid=2, version=11, reply=5)
DEBUG:caproto.bcast:VersionRequest(priority=10, version=11)
DEBUG:caproto.bcast:SearchRequest(name='BIOCARS:SERVERS.PICO1.BIOCARS.21.RUNNING', cid=3, version=11, reply=5)
DEBUG:caproto.bcast:VersionRequest(priority=10, version=11)
DEBUG:caproto.bcast:SearchRequest(name='BIOCARS:SERVERS.PICO1.BIOCARS.23.RUNNING', cid=4, version=11, reply=5)
DEBUG:caproto.circ:EventAddResponse(data=array([21, 64,  1, ..., 21, 48,  1], dtype=int16), data_type=<ChannelType.INT: 1>, data_count=18432000, status=CAStatusCode(name='ECA_NORMAL', code=0, code_with_severity=1, severity=<CASeverity.SUCCESS: 1>, success=1, defunct=False, description='Normal successful completion'), subscriptionid=0, metadata=None)
```

**Comment by vstadnytskyi** [comment]
I was thinking that the load is too high so I reduced the rate to 7.8 FPS. I don't get the message "High Load" now but the caproto server still crashes and there is no warning or errors anywhere.

**Comment by danielballan** [comment]
Hi @vstadnytskyi! The high load mechanism take the same approach as the reference implementation (or least we are trying to). When the hardware is providing updates faster than we can send them over the network, we start sending them in batches of greater than 1 message per network packet. This reduces the overhead per update, at the cost of some additional latency. If we get _really_ backed up, we start dropping old messages that we haven't managed to send yet.

It is described in this comment and surrounding ones. https://github.com/caproto/caproto/pull/319/files#diff-d075696c6016900267e3e99621d50d36170941005ce21e06371f3b87f76281dfR247-R253 

We have a bit of "hair trigger" here. A "batch" of two messages is hardly a very large batch, and so we should probably not be shifting so readily into batch mode. We need to tune the parameters that control when the flip over into batching updates.

However, none of this should crash caproto. In fact the idea is to _avoid_ letting and high-volume producer create ballooning queues. Can you link us to the IOC for further investigation?

**Comment by vstadnytskyi** [comment]
@danielballan Thank you! This is very useful and the comment in the link is quite explanatory.
