### ISSUE TITLE
Preprocessing value bottlenecks

### ISSUE THREAD

**Issue by klauer** [caproto/caproto#705]
Background
------------

Preprocessing conversions of data happen in `ChannelData` to keep values passed along by any source - in many different potential forms - stored in a consistent manner:
https://github.com/caproto/caproto/blob/03cff19954c81a40e679d592d26b6a9277032b65/caproto/_data.py#L265-L298

These conversions can be tricky and break things unexpectedly. Changes should be approached cautiously - with more test cases added where missing/needed.

Problem
----------

There is special preprocessing for byte strings:
https://github.com/caproto/caproto/blob/03cff19954c81a40e679d592d26b6a9277032b65/caproto/_data.py#L980-L1006

And strings with associated encodings:
https://github.com/caproto/caproto/blob/03cff19954c81a40e679d592d26b6a9277032b65/caproto/_data.py#L1036-L1060

Particularly the `map()` call in these can be an awful bottleneck - especially when the passed-in value starts of as either an already-valid `array.array` or a `np.ndarray` (as shown to perform terribly in #704). 

Possibility 1
---------------
Backends could perform this processing in a way that makes sense for them - numpy can handle its `ndarray`, and `array` can handle these string/byte conversions appropriately - and quickly.

Possibility 2
-------------
* Create some string/byte-handling utilities outside of the backends
* Possibly use the array interface (https://numpy.org/doc/stable/reference/arrays.interface.html) to not require numpy here as well
* Alternatively, a `try/except ImportError` for `numpy`

Other ideas
------------
Any other ideas/thoughts?

**Comment by danielballan** [comment]
:+1: for `__array_interface__` if it works.

**Comment by klauer** [comment]
Thank you for the input, @danielballan and @tacaswell. Will see what I can do here.
