### ISSUE TITLE
Custom argument as input to caproto python program

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#706]
Hello All,

first I absolutely love caproto, great job! I wish I could help more with the development but right now I am mostly finding issues. I have built several very well performing and sometimes demanding CA servers. One of the last servers I made was for FLIR cameras which is very demanding and it worked, maybe not as well as I wanted :) but this is a very demanding application.

One thing I am struggling with is how to write a generic CA server for a specific device. I am trying to have a caproto python code that takes configuration parameters from a text file and initializes a device-level application. there is a sequence of events like find a USB device by its' PID and VID and confirms the serial number and launch the data collection.

The main idea is to have one caproto server code that I can customize with a configuration file.

**For example DATAQ DI-2008**
    
``` shell
python3 dataq_di_2008.py '/pathtofile/config_DI_2008_tower.conf'
```

I get the error:

``` shell
usage: device.py [-h] [--prefix PREFIX] [-q | -v] [--list-pvs] [--async-lib {asyncio,curio,trio}] [--interfaces INTERFACES [INTERFACES ...]]
device.py: error: unrecognized arguments: /pathtofile/config_DI_2008_tower.conf
```    

I understand that my argument is not a standard argument that caproto takes(e.g.  `--list-pvs --prefix my_custom_prefix:`)

**Is there a way to send a custom argument to caproto from the terminal similar to my attempt above?** 

I tried to check help (-h) but it seems there is no way to add a custom input argument.

```
python3 device.py -h
usage: device.py [-h] [--prefix PREFIX] [-q | -v] [--list-pvs] [--async-lib {asyncio,curio,trio}] [--interfaces INTERFACES [INTERFACES ...]]

An IOC with three uncoupled read/writable PVs

Scalar PVs
----------

Vectors PVs
-----------
AIO
DIO

optional arguments:
  -h, --help            show this help message and exit
  --prefix PREFIX
  -q, --quiet           Suppress INFO log messages. (Still show WARNING or higher.)
  -v, --verbose         Show more log messages. (Use -vvv for even more.)
  --list-pvs            At startup, log the list of PV names served.
  --async-lib {asyncio,curio,trio}
                        Which asynchronous library to use. Default is asyncio.
  --interfaces INTERFACES [INTERFACES ...]
                        Interfaces to listen on. Default is 0.0.0.0. Multiple entries can be given; separate entries by spaces.

caproto version 0.6.0
```

Just so we are on the same page:
I am not sure how to call parameters followed by a command. for example, Linux command `ls` can be followed by arguments `-l` resulting in `ls -l`. So I call it `command -arguments`

**Comment by klauer** [comment]
Glad to hear your results have been mostly positive, @vstadnytskyi. Thanks for continuing to push for caproto to be even better.

For reference, argument parsing happens with these 2 functions:
https://github.com/caproto/caproto/blob/03cff19954c81a40e679d592d26b6a9277032b65/caproto/server/server.py#L1556-L1692

At the moment, the easiest way to get a custom argument into an IOC is by specifying a macro with a default value - e.g., `macros={'config': 'tower.conf'}`. These macros would be accessible in your `PVGroup` `__init__` as the `macros` kwarg. (relevant example: https://github.com/caproto/caproto/blob/03cff19954c81a40e679d592d26b6a9277032b65/caproto/ioc_examples/macros.py#L14-L19)

This is an easy hook, but not an ideal one in your case. The second best alternative would be to grab the `ArgumentParser` instance from `template_arg_parser`, add your arguments, and then reimplement/tweak `split_args` and `ioc_arg_parser` for your purposes.

The last alternative would just be to write your own `ArgumentParser` from scratch.
