### ISSUE TITLE
Catch invalid packets, invalid command ID exceptions and re-raise with user-friendly messages

### ISSUE THREAD

**Issue by klauer** [caproto/caproto#713]
Issue
------
Based on #711 - unhelpful exceptions raised and dumped directly to the user

Path forward
-------------
Should probably have a new exception type for this. In this scenario, the original exception is `KeyError` - so perhaps `InvalidCommandID(CaprotoError, KeyError)`?

Something like `InvalidCommandID("Packet with bad command ID 0xABC was received (header details here)")`

Background
------------
Security scanners as in the original issue are notorious for sending such IOC-crashing messages - we've recently run into that ourselves at SLAC. Surprisingly, caproto server in this instance fares better than epics-base.

Part of the problem is that there's no magic in the V3 CA header, so security scanners sending along strings such as `GET / HTTP/1.1` are deserialized into a `MessageHeader` and it's equally as valid as any other packet.

**Comment by danielballan** [comment]
We could even check if it looks like an HTTP request and say so (once we know we are failing anyway). What does epics-base do when it gets hit with random HTTP requests?

**Comment by klauer** [comment]
> What does epics-base do when it gets hit with random HTTP requests?

It dumps out something not so useful like this, and on crashes on occasion:
```
CAS: Request from x.y.z.148:42174 => cmmd=769 cid=0x3b0000 type=7 count=0 postsize=2560
CAS: Request from x.y.z.148:42174 =>   available=0x0       N=0 paddr=(nil)
```
