### ISSUE TITLE
Related to #457, can't run example on Mac OS X

### ISSUE THREAD

**Issue by toqduj** [caproto/caproto#717]
I get the same issue as #457 , running on a Mac (10.15.7), trying to run the four-line caproto example:
$ pip install caproto
$ python3 -m caproto.ioc_examples.simple --list-pvs
results in:

[I 18:01:41.431       server:  133] Asyncio server starting up...
[I 18:01:41.432       server:  146] Listening on 0.0.0.0:5064
[I 18:01:41.433       server:  205] Server startup complete.
[I 18:01:41.434       server:  207] PVs available:
    simple:A
    simple:B
    simple:C
[E 18:01:41.434        utils:   59] <caproto.asyncio.utils._DatagramProtocol object at 0x7fd044419c10> receive error
    Traceback (most recent call last):
      File "/Users/brian/opt/anaconda3/envs/lab39/lib/python3.8/asyncio/selector_events.py", line 1046, in sendto
        self._sock.sendto(data, addr)
    OSError: [Errno 49] Can't assign requested address

**Comment by klauer** [comment]
Hi @toqduj - thanks for the report.

You may get better debugging output by appending `-vv` to your `python3` line (`v` for `verbose`).

If you have a chance, please send along that debug output as well in this issue.

I'd expect that it's having issues sending UDP broadcast packets for beacons - which indicate to other hosts on your network that an IOC is running. Assuming I've guessed the correct source of the messages: these settings may require further information about your network setup. These are freely configurable through environment variables named after the originals from epics-base:
https://github.com/caproto/caproto/blob/16b06d1ffd97f8c850db315c1215cfdb829f85f4/caproto/_utils.py#L277-L280

Their settings may be not be very intuitive. For example, to redirect beacons to a specific subnet `10.0.0.255`, `EPICS_CAS_BEACON_ADDR_LIST=10.0.0.255 EPICS_CAS_AUTO_BEACON_ADDR_LIST=NO python3 -m caproto.ioc_examples.simple --list-pvs -vvv`.

Though annoying and spammy, such beacon send failure messages will not likely interfere much with clients trying to interact with your IOC.

**Comment by toqduj** [comment]
Thanks for the answer (and sorry for the slow response, it didn't show up in my Github notifications list or I missed it). 

I looked at the network configuration on my laptop (where I'm testing on), and the internal network here has IPs in the range 192.168.178.x, with the broadcast address at 255 (as expected, I think). So I tried the following:

```
EPICS_CAS_BEACON_ADDR_LIST=192.168.178.255 EPICS_CAS_AUTO_BEACON_ADDR_LIST=NO python3 -m caproto.ioc_examples.simple --list-pvs -vvv
[D 10:53:53.505       common:  711] EPICS_CA_SERVER_PORT set to 5064. This is the UDP port to be used for searches, and the first TCP server port to be tried.
[I 10:53:53.505       server:  133] Asyncio server starting up...
[I 10:53:53.506       server:  146] Listening on 0.0.0.0:5064
[D 10:53:53.507       server:  194] UDP socket bound on 0.0.0.0:5064
[I 10:53:53.507       server:  205] Server startup complete.
[I 10:53:53.507       server:  207] PVs available:
    simple:A
    simple:B
    simple:C
[D 10:53:53.507       common: 1004] Will send beacons to ['192.168.178.255:5065']
[D 10:53:53.507 _broadcaster:   94] (1 of 1) Beacon(version=13, server_port=5064, beacon_id=0, address='0.0.0.0')
[D 10:53:53.548 _broadcaster:   94] (1 of 1) Beacon(version=13, server_port=5064, beacon_id=1, address='0.0.0.0')
[D 10:53:53.633 _broadcaster:   94] (1 of 1) Beacon(version=13, server_port=5064, beacon_id=2, address='0.0.0.0')
[D 10:53:53.797 _broadcaster:   94] (1 of 1) Beacon(version=13, server_port=5064, beacon_id=3, address='0.0.0.0')
[D 10:53:54.119 _broadcaster:   94] (1 of 1) Beacon(version=13, server_port=5064, beacon_id=4, address='0.0.0.0')
[D 10:53:54.759 _broadcaster:   94] (1 of 1) Beacon(version=13, server_port=5064, beacon_id=5, address='0.0.0.0')
^C[I 10:53:55.165       server:  212] Server task cancelled. Will shut down.
[I 10:53:55.165       server:  222] Server exiting....

```
This then successfully starts the IOC and sets it broadcasting. However, if I try the same in another terminal window to set values on that IOC, it doesn't send (or get):

```
EPICS_CAS_BEACON_ADDR_LIST=192.168.178.255 EPICS_CAS_AUTO_BEACON_ADDR_LIST=NO caproto-get simple:A -vvv
[D 11:00:29.911     repeater:  221] Another repeater is already running; will not spawn one.
[D 11:00:29.912       client:   57] Registering with the Channel Access repeater.
[D 11:00:29.912 _broadcaster:   94] (1 of 1) RepeaterRegisterRequest(client_address='0.0.0.0')
[D 11:00:29.913       _utils:  535] Netifaces unavailable; using 127.0.0.1 as local address
[D 11:00:29.914       client:   72] Searching for 'simple:A'....
[D 11:00:29.914 _broadcaster:   94] (1 of 2) VersionRequest(priority=0, version=13)
[D 11:00:29.914 _broadcaster:   92] (2 of 2) SearchRequest(name='simple:A', cid=0, version=13, reply=5)
[D 11:00:29.914       client:   84] 0.0.0.0:57737 --->>> 255.255.255.255:5064 2 commands 48B
Traceback (most recent call last):
  File "/Users/brian/opt/anaconda3/envs/lab39/lib/python3.8/site-packages/caproto/sync/client.py", line 88, in send_search
    udp_sock.sendto(bytes_to_send, dest)
OSError: [Errno 49] Can't assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/brian/opt/anaconda3/envs/lab39/bin/caproto-get", line 8, in <module>
    sys.exit(main())
  File "/Users/brian/opt/anaconda3/envs/lab39/lib/python3.8/site-packages/caproto/commandline/get.py", line 170, in main
    response = read(pv_name=pv_name,
  File "/Users/brian/opt/anaconda3/envs/lab39/lib/python3.8/site-packages/caproto/sync/client.py", line 335, in read
    chan = make_channel(pv_name, udp_sock, priority, timeout)
  File "/Users/brian/opt/anaconda3/envs/lab39/lib/python3.8/site-packages/caproto/sync/client.py", line 143, in make_channel
    address = search(pv_name, udp_sock, timeout)
  File "/Users/brian/opt/anaconda3/envs/lab39/lib/python3.8/site-packages/caproto/sync/client.py", line 107, in search
    send_search()
  File "/Users/brian/opt/anaconda3/envs/lab39/lib/python3.8/site-packages/caproto/sync/client.py", line 91, in send_search
    raise ca.CaprotoNetworkError(f"Failed to send to {host}:{port}") from exc
caproto._utils.CaprotoNetworkError: Failed to send to 255.255.255.255:5064

```
Seems like it needs different environment variables to be set? 

The intention is for me to eventually talk to IOCs from a Jupiter notebook, so I'm not sure environment variables is the way to go for configuring the network addresses. Is there a class I can instantiate and point at the right address for this? Thanks a lot for helping!

**Comment by klauer** [comment]
Thanks for the very detailed response, @toqduj. This line indicated why your network settings weren't automatically determined correctly:

`[D 11:00:29.913       _utils:  535] Netifaces unavailable; using 127.0.0.1 as local address`

caproto prides itself on having no actual dependencies, but at least a couple make it much more usable: `netifaces` (and probably numpy). If you install `netifaces` into that same environment, this should hopefully resolve your issue. It will automatically discover all of the settings that you just listed by way of `ifconfig`: determining appropriate broadcast addresses, interfaces to listen on, and so on.

A shortcut to doing this to start with is `pip install caproto[standard]` instead of the bare `pip install caproto`. 

(To fix your scenario manually, you'd have to set `EPICS_CA_ADDR_LIST=192.168.178.255` and `EPICS_CA_AUTO_ADDR_LIST=NO`. Given your target is a reusable notebook, this is a less-than-ideal solution, for sure!)

**Comment by toqduj** [comment]
Thanks for bearing with me along the long troubleshooting, @klauer. Indeed, your solution (pip install caproto[standard]) fixed my issues and it now happily runs on a MacBook. onwards and forwards ;).

**Comment by klauer** [comment]
Great - glad that worked! Thanks for closing the loop on this. 👍
