### ISSUE TITLE
Rearrange IOC examples and improve documentation thereof

### ISSUE THREAD

**Issue by klauer** [caproto/caproto#738]
(I asked for input on this in Nikea #caproto but didn't even get an emoji response there like usual, so I suppose the task is solely up to me to figure out. Regardless, input is _very much_ appreciated here.)

Broad categories:
* How do I do very basic things
    * Basic `pvproperty` introduction - what data types are supported? (#519)
* How do I do very common tasks:
    * Hooks: `startup`, `shutdown`, `scan`
    * Hooks: `putter` (do not include _any_ `getter` except in advanced)
    * Patterns for updating `PVGroup` when communicating with an actual device (or async client of sorts, where one request can update many properties' values)
    * How do I handle records and what are the limitations there?
    * How do I add a client to monitor other PVs? (asyncio client) Can I use input/output/etc links like in EPICS? (_No_)
    * How do I get custom arguments into my IOC without rewriting the arg parser? (#706)
    * Macros and how to use them
* How do I use the alternative methods of building IOCs?
   * `PVSpec`-based 
   * `ChannelData`-based
* How do I do (advanced thing here)
  * The pathological examples belong here

Tie in some documentation tweaks as well to reflect this rearranging, and provide better flow for new users.

I think the above indicates some new examples should be written, or older ones should be reworked/changed entirely

Ties in with #721 
Ties in with #663 
Ties in with #519 
Ties in with #706

**Comment by danielballan** [comment]
I need to make good on https://github.com/bluesky/ophyd/pull/965 before I let myself play with this, but I'm in. Caproto Server Docs Refresher Summer 2021. :palm_tree: This is a great check list.

How do you feel about following the structure recently applied to Databroker and proposed in that Ophyd PR, and then gradually building out these how-to guides?

**Comment by klauer** [comment]
Sounds good. 

My time scale is a bit shorter than yours, though. I'll be working on the above examples and partial restructuring in the near-term.
