### ISSUE TITLE
Document meaning of "High load. Batched 2 commands" and warn only if above a threshold

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#780]
I am getting this message but I do not how to make sense out of it. See below. Is it something to do with sending too much data or sending to many updates to PVs? 

```
[I 11:50:39.604       common:  390] High load. Batched 2 commands (168B) with 0.0003s latency.
[I 11:50:49.370       common:  390] High load. Batched 2 commands (168B) with 0.0033s latency.
[I 11:50:52.602       common:  390] High load. Batched 4 commands (416B) with 0.0005s latency.
[I 11:50:58.699       common:  390] High load. Batched 2 commands (168B) with 0.0002s latency.
[I 11:51:00.885       common:  390] High load. Batched 2 commands (168B) with 0.0008s latency.
[I 11:51:01.226       common:  390] High load. Batched 4 commands (416B) with 0.0002s latency.
[I 11:51:09.341       common:  390] High load. Batched 2 commands (168B) with 0.0006s latency.
[I 11:51:09.428       common:  390] High load. Batched 2 commands (208B) with 0.0012s latency.
[I 11:51:11.877       common:  390] High load. Batched 2 commands (168B) with 0.0124s latency.
[I 11:51:12.216       common:  390] High load. Batched 4 commands (416B) with 0.0003s latency.
[I 11:51:20.059       common:  390] High load. Batched 2 commands (168B) with 0.0008s latency.
[I 11:51:23.274       common:  390] High load. Batched 2 commands (168B) with 0.0002s latency.
[I 11:51:23.656       common:  390] High load. Batched 4 commands (416B) with 0.0005s latency.
[I 11:51:28.470       common:  390] High load. Batched 2 commands (168B) with 0.0006s latency.
[I 11:51:28.681       common:  390] High load. Batched 2 commands (168B) with 0.0009s latency.
[I 11:51:30.737       common:  390] High load. Batched 2 commands (168B) with 0.0143s latency.
[I 11:51:33.044       common:  390] High load. Batched 2 commands (168B) with 0.0069s latency.
[I 11:51:33.393       common:  390] High load. Batched 4 commands (416B) with 0.0003s latency.
[I 11:52:34.463       common:  390] High load. Batched 4 commands (416B) with 0.0002s latency.
[I 11:53:36.582       common:  390] High load. Batched 4 commands (416B) with 0.0002s latency.
[I 11:54:34.552       common:  390] High load. Batched 4 commands (416B) with 0.0002s latency.
```

**Comment by tacaswell** [comment]
The server has two modes of sending out monitors.  If they are coming in slow enough, it sends them one-at-a-time.  If they are coming in fast enough, it will try to batch them.    If we stuck with one-at-a-time and were not keeping up eventually we would fall infinitely far behind (and either OOM or start dropping things on the floor).  On the other hand, if we always batched we would be setting some artificial latency floor on how quickly we could get an update out to clients based how long we wait for more information before deciding the batch should go out.

This long entry is telling you that at some points (without knowing exactly what you are doing hard to guess the other circumstances) that it is falling back to batching.   This could be that you are sitting at a sustained rate that is _just_ under what we can keep up with and every so often we lose a race and switch to patch mode or it could be that you are sending out really bursty updates that temporarily get faster than we can send things out.

**Comment by klauer** [comment]
We should introduce a threshold that says "if batching happens and latency is under this threshold, don't warn the user".  200µs of latency is not worth reporting here.
