### ISSUE TITLE
Writing a motor controller IOC... any tips/guidelines?

### ISSUE THREAD

**Issue by toqduj** [caproto/caproto#781]
Hi all, 

I need to write an IOC for a Trinamics motor controller board (probably leveraging pytrinamics) using their TMCL protocol over IP. It's a bit bigger than the run-of-the-mill IOCs I've written so far for hotplates, syringe injectors and arduinos, so could use a few tips on which structure ideally to adhere to. I saw there's a template in the caproto examples, if that's a good start?

B.

**Comment by toqduj** [comment]
*polite cough..*

**Comment by klauer** [comment]
https://caproto.github.io/caproto/master/iocs.html#structure-an-ioc-when-talking-to-a-real-piece-of-hardware perhaps?

**Comment by toqduj** [comment]
Thanks, we're doing that for our other, simpler hardware, I was more wondering if there is a listing or example somewhere on how to correctly name and group the PV entries so the IOC resembles a standard EPICS "motor record"?

**Comment by klauer** [comment]
This mocks up the fields of the motor record to some degree and is the most complete example I'm aware of: https://github.com/caproto/caproto/blob/master/caproto/ioc_examples/fake_motor_record.py

**Comment by toqduj** [comment]
Ah super, thanks! We'll give that a shot.

**Comment by toqduj** [comment]
Got the motor controller IOC working, thanks again for the pointers!
