### ISSUE TITLE
BUG: Using lower-level PVSpec with kwarg `read_only=True` results in a PV that is not read only.

### ISSUE THREAD

**Issue by marrable** [caproto/caproto#783]
I am relatively new to caproto, so I apologise if this is the intended behaviour and I am missing the necessary context.

#### Behaviour:
I was writing a simple IOC based on the [`no_pvproperty.py`](https://github.com/caproto/caproto/blob/master/caproto/ioc_examples/no_pvproperty.py) example and realised that even when I had specified `read_only=True` for a boolean value PVSpec, I was still able to change the PV at runtime via `caput <PV_NAME> <VALUE>` on a separate terminal.

#### Steps to Reproduce:
``` Python
#!/usr/bin/env python3
from caproto.server import PVSpec, ioc_arg_parser, run

pv_a = PVSpec(
    name="a",
    value=True,
    record='bi',
    doc='A bool',
    read_only=True
)

pvdb = {
    pvspec.name: pvspec.create(group=None)
    for pvspec in [pv_a]
}

def main():
    global pvdb, pv_a
    print("pvdb contents:", pvdb)
    print(pv_a.read_only)

    ioc_options, run_options = ioc_arg_parser(
        default_prefix='pvspec:',
        desc="A simple IOC without using the PVGroup-style class syntax."
    )
    # It's up to you to add on the prefix and support any other ioc_options:
    pvdb = {
        ioc_options['prefix'] + name: data
        for name, data in pvdb.items()
    }
    run(pvdb, **run_options)
```
Running this sample above (which is a stripped back version of the `no_pvproperty.py` example) perform a `caput` in a separate terminal to change the PV.

#### Potential Root Cause
In [`server.py`](https://github.com/caproto/caproto/blob/master/caproto/server/server.py) the following type maps are defined:
``` Python
pvspec_type_map = {
    str: PvpropertyChar,
    bytes: PvpropertyByte,
    int: PvpropertyInteger,
    float: PvpropertyDouble,
    bool: PvpropertyBoolEnum,
    enum.IntEnum: PvpropertyEnum,

    ChannelType.STRING: PvpropertyString,
    ChannelType.INT: PvpropertyShort,
    ChannelType.LONG: PvpropertyInteger,
    ChannelType.DOUBLE: PvpropertyDouble,
    ChannelType.FLOAT: PvpropertyFloat,
    ChannelType.ENUM: PvpropertyEnum,
    ChannelType.CHAR: PvpropertyChar,
}

# Auto-generate the read-only class specification:
pvspec_type_map_read_only = {
    dtype: globals()[f'{cls.__name__}RO']
    for dtype, cls in pvspec_type_map.items()
}
```
The read only type map is a duplicate of the regular one, but adds the `RO` suffix.

Then we have the `get_data_class(self, group=None)` method of `PVSpec` (line 534 in [`server.py`](https://github.com/caproto/caproto/blob/master/caproto/server/server.py)) which is defined as follows:
``` Python
    def get_data_class(self, group=None):
        """
        Return the data class for a given PVSpec in a group.
        Parameters
        ----------
        group : PVGroup, optional
            If unspecified, module-global type maps will be used.
        """
        if group is None:
            type_map = pvspec_type_map
            type_map_read_only = pvspec_type_map  # <--- MAYBE BUG HERE
        else:
            type_map = group.type_map
            type_map_read_only = group.type_map_read_only

        dtype = self.dtype

        # A special case for integer enums:
        if inspect.isclass(dtype) and issubclass(dtype, enum.IntEnum):
            dtype = enum.IntEnum

        if self.read_only:
            return type_map_read_only[dtype]

        return type_map[dtype]
```
In the instance that `group` is `None`, it looks like `type_map_read_only` is incorrectly set to the regular type map `pvspec_type_map`, allowing the type to be writable when it should be read only. Again, not sure if this is intended behaviour or not, but I will submit a PR with this issue since it appears to be a one line fix.

**Comment by klauer** [comment]
Closed by #784 👍
