### ISSUE TITLE
Writing a C++ CA client that communicates with caproto-based server

### ISSUE THREAD

**Issue by dvucko** [caproto/caproto#793]
Please excuse me if I missed something elementary, but I wonder if it's possible to use caproto to set up a basic CA server that will publish some custom PVs to a standalone CA client written in C++? I'd like a simple server that updates some array etc. and sends them to a production-grade C++ client. Is such a connection possible?

**Comment by tacaswell** [comment]
Yes, caproto is a compliant with the CA protocol (on both the client and server side).  Clients are naive to the implementation language of the server and the server is naive to the implementation language of the client.

https://github.com/caproto/caproto/blob/master/caproto/tests/test_catvs.py tests the server against https://github.com/mdavidsaver/catvs 

What your describing is one of the more common uses of caproto :)

**Comment by dvucko** [comment]
Thank you for a quick response, Thomas. I was expecting this to be the case, but as an EPICS newbie I wanted to be sure before a deeper investigation into the technicalities.
