### ISSUE TITLE
Python 3.10: asyncio `loop` parameter was removed

### ISSUE THREAD

**Issue by mr-kenhoff** [caproto/caproto#800]
In python version 3.10 the asyncio `loop` parameter was removed ([source](https://docs.python.org/3/whatsnew/3.10.html#whatsnew310-removed)) which is heavily used in `caproto/asyncio/server.py`. 

The manual loop handling could be removed, which also simplifies the code a bit. However, this would break compatibility with python 3.6.

Whats the roadmap for python 3.6 support? Any alternative solutions are welcome. I am happy to make the necessary changes.

**Comment by klauer** [comment]
The next release - if we ever get to it - will be 3.8+ only. Contributions are always welcome!

**Comment by tacaswell** [comment]
The changes for this already on the main branch.

**Comment by mr-kenhoff** [comment]
Thanks for your fast replies! I only tried the pypi version.
