### ISSUE TITLE
Strict typing and Caproto

### ISSUE THREAD

**Issue by mfurseman** [caproto/caproto#804]
I've been using Caproto in a library with strict static typing, this is going okay and the existing type hints have been useful for auto-generating stubs, however at the moment there's a gap between the detail in the existing typing and what's needed for strict typing. 

What are your plans for this? I imagine if you are not using strict typing yourself there is little motivation to add them. As far as I can tell, the 'proper' way of adding stubs is to seperate them for ones source in `*.pyi` files.

**Comment by klauer** [comment]
There are no plans for this, but contributions are always welcome.

**Comment by clintonroy** [comment]
I think it's fine to give us PRs that incrementally improve the typing within the caproto code, rather than putting things in extra files. once we get to a certain point, we'll be able to add mypy checking to automatic pipelines

**Comment by mfurseman** [comment]
Okay, thanks for your comments. I will consider a PR for some of the areas I've been working in. At the moment I'm using PyRight as it is more complete regarding changes for Python3.11 than mypy. I imagine that won't be an issue here as this codebase targets `python >= 3.8`.
