### ISSUE TITLE
Repository links for Caproto-written IOCs?

### ISSUE THREAD

**Issue by toqduj** [caproto/caproto#818]
We've now written quite a few IOCs for various hardware using Caproto. Would it be an idea to collect these somewhere?

**Comment by danielballan** [comment]
We could:
* Link to known repos of caproto IOCs from the caproto documentation
* Make one or more repos within the Caproto GH organization

Either (or both) sounds reasonable to me.

**Comment by klauer** [comment]
Alternatively, caproto's top-level `README` file is almost entirely empty. A contribution to fill it up a bit with some basic details about the project along with a list of existing IOCs (including those you've written) would be much appreciated.

**Comment by toqduj** [comment]
Ok, I'll tidy up my IOCs and put them in repositories, then update the
caproto TL-Readme and make a PR. I'll get back on this in three weeks.

**Comment by asoderq** [comment]
I'd be very interested in looking at existing IOCs. If you know any existing uploaded also elsewhere perhaps?

**Comment by klauer** [comment]
Here's the ones I'm aware of:
* https://github.com/pcdshub/archstats/  EPICS Archiver Appliance statistics IOC 
* https://github.com/slaclab/simulacrum simulacrum services
* https://github.com/pcdshub/solid-attenuator  LCLS Solid Attenuator System Calculator IOC 
* https://github.com/pcdshub/sim-ioc/ Miscellaneous simulation IOC stuff
* https://github.com/pcdshub/fluke_985 Fluke 985 particle counter IOC
* https://github.com/caproto/caproto-rpi raspberry Pi IOCs (@danielballan )
* https://github.com/caproto/caproto_ios Ancient and likely defunct Apple iOS caproto IOCs
* https://github.com/NSLS-II/archiver-proxy archiver proxy (@tacaswell )
* https://github.com/prjemian/dhtioc DHT-22  (@prjemian)

Related:
* https://github.com/pcdshub/cookiecutter-caproto-ioc cookiecutter for IOCs
* https://github.com/pcdshub/cookiecutter-caproto-ioc-startup startup script for above cookiecutter
* https://github.com/klauer/caproto-image-viewer defunct image viewer (new maintainer would be welcome)

**Comment by toqduj** [comment]
One more: a motor controller IOC for Trinamics boards (by me). Currently only tested on the six-axis 6214, but their TMCL language is pretty universal. https://github.com/BAMresearch/Trinamic_TMCM6214_TMCL_IOC
