### ISSUE TITLE
More benchmarks

### ISSUE THREAD

**Issue by danielballan** [caproto/caproto#82]
Some ideas:

- [x] Measure time it takes to open N Channels. (needs some work...)
- [ ] How fast can a server issue Events?
- [ ] How fast can a client process Events before it falls behind a server?
- [x] How fast can all clients process get large waveforms?
- [x] How fast can all clients process put large waveforms?

**Comment by klauer** [comment]
Our benchmarks were nuked into orbit - we should open a new issue indicating the direction we're going to go and the benchmarks we'd like to see.
