### ISSUE TITLE
Resource leak in caproto.threading.pyepics_compat

### ISSUE THREAD

**Issue by smarsching** [caproto/caproto#824]
At the moment, `caproto.threading.pyepics_compat.caget_many` creates a new CA context every time the function is called, unless a context object is passed explicitly. This is due to the following code in `caget_many`:

```py
    if context is None:
        context = Context(PV._default_context.broadcaster)
```

This means that when this function is called repeatedly, many context objects are created, which potentially leads to many connections being established to the same CA server, which can result in resource exhaustion on the server (this is how we noticed this behavior).

I believe that the fix is rather simple: The default context object, that is also used by the other functions in this module should also be used by the`caget_many` function. For example, `get_pv` uses the following code:

```
    if context is None:
        context = PV._default_context
```

I can open a PR for this fix, I just wanted to verify first that this is indeed a bug not intended behavior for some reason.

**Comment by klauer** [comment]
That's almost certainly a bug - thanks for reporting. I agree with your proposed fix and would be happy to merge it in if you open the PR.

**Comment by danielballan** [comment]
Agreed!

**Comment by smarsching** [comment]
PR has been created as #825.
