### ISSUE TITLE
Failed to send beacon error

### ISSUE THREAD

**Issue by wigging** [caproto/caproto#842]
I'm on macOS 14.3.1 and using Python 3.9 to run caproto in a virtual environment (venv). I installed caproto with
`pip install "caproto[standard]"` in the virtual environment. When I run `python -m caproto.ioc_examples.simple`, I get the errors shown below. It suggests that I set some environment variables but what do I use for `EPICS_CAS_BEACON_ADDR_LIST`?

```
[I 13:03:39.504       server:  152] Asyncio server starting up...
[I 13:03:39.505       server:  159] Listening on 0.0.0.0:5064
[I 13:03:39.506       server:  196] Server startup complete.
[E 13:03:39.547       common: 1133] Failed to send beacon to ('255.255.255.255', 5065). Try setting EPICS_CAS_AUTO_BEACON_ADDR_LIST=no and EPICS_CAS_BEACON_ADDR_LIST=<addresses>.
    Traceback (most recent call last):
      File "/Users/g72/Desktop/ORNL/ESPD/caproto-example/venv/lib/python3.9/site-packages/caproto/asyncio/utils.py", line 145, in send
        self.transport.send(bytes_to_send)
    OSError: [Errno 49] Can't assign requested address
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Users/g72/Desktop/ORNL/ESPD/caproto-example/venv/lib/python3.9/site-packages/caproto/server/common.py", line 1131, in broadcast_beacon_loop
        await sock.send(bytes_to_send)
      File "/Users/g72/Desktop/ORNL/ESPD/caproto-example/venv/lib/python3.9/site-packages/caproto/asyncio/utils.py", line 147, in send
        raise ca.CaprotoNetworkError(
    caproto._utils.CaprotoNetworkError: Failed to send to 255.255.255.255:5065
[E 13:03:39.630       common: 1133] Failed to send beacon to ('255.255.255.255', 5065). Try setting EPICS_CAS_AUTO_BEACON_ADDR_LIST=no and EPICS_CAS_BEACON_ADDR_LIST=<addresses>.
    Traceback (most recent call last):
      File "/Users/g72/Desktop/ORNL/ESPD/caproto-example/venv/lib/python3.9/site-packages/caproto/asyncio/utils.py", line 145, in send
        self.transport.send(bytes_to_send)
    OSError: [Errno 49] Can't assign requested address
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Users/g72/Desktop/ORNL/ESPD/caproto-example/venv/lib/python3.9/site-packages/caproto/server/common.py", line 1131, in broadcast_beacon_loop
        await sock.send(bytes_to_send)
      File "/Users/g72/Desktop/ORNL/ESPD/caproto-example/venv/lib/python3.9/site-packages/caproto/asyncio/utils.py", line 147, in send
        raise ca.CaprotoNetworkError(
    caproto._utils.CaprotoNetworkError: Failed to send to 255.255.255.255:5065
```

**Comment by tacaswell** [comment]
Do you mean to be running an IOC this is visible on the network?  

If not, launch it as `python -m caproto.ioc_examples.simple --interfaces 127.0.0.1` to only bind the local host address.

if so, set EPICS_CAS_BEACON_ADDR_LIST to a broadcast address you can send to (e.g. `192.168.86.255`).  This looks like something in lab networking is say "no you may not broadcast to EVERYONE" (which to be fair is sensible) but I'm not going to speculate on what at what level is doing that....

**Comment by wigging** [comment]
Setting `--interfaces` isn't necessary. If I set `EPICS_CAS_AUTO_BEACON_ADDR_LIST=no` and `EPICS_CAS_BEACON_ADDR_LIST=192.168.86.255` then run `python -m caproto.ioc_examples.simple` everything works fine. Where did `192.168.86.255` come from and why that particular address?

**Comment by tacaswell** [comment]
that is what it should be on my home network (via a residential grade router), you should make it set the netmask on your network.

**Comment by wigging** [comment]
I didn't have to do any of this previously with caproto. I wonder if it's related to the macOS upgrade I did last week. @tacaswell What operating system and Python version are you using? Do you have to set these environment variables too?

**Comment by tacaswell** [comment]
This is a lower level networking thing and should be independent of Python version.

I do not have to set this on my desktop, but we do have to set these ENVS for caproto IOCs that are running on the floor (which are running on a managed network).

It is possible that macOS locked down their network stack a bit more, but I suspect it is more likely related to the lab network.

One test would be to unplug / turn of wifi and see if you still see the issue.
